winder/Universal-G-Code-Sender

.gitignore, pom.xml
Hi,
as it is required since UGS 1.7, the Java source and target in the pom.xml should also be 1.7.
I also added IntelliJ IDEA project files to the ignore list.
Regards
Martin
=> declare compiler source and target in pom.xml to 1.7

src/com/willwinder/universalgcodesender/gcode/GcodeParser.java, src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, src/com/willwinder/universalgcodesender/model/GUIBackend.java
When opening large files, the preprocessing takes a very long time.  By compiling the regular expressions once rather than using the string.replaceAll methods, we can save significant time.
On my laptop, I opened a gcode file with 7233438 lines (laser image raster)
with my changes - 16155ms
master - 56178ms 
I believe this addresses at least part of Issue #168.
=> performance enhancement - optimize file preprocessing

src/com/willwinder/universalgcodesender/MainWindow.form, src/com/willwinder/universalgcodesender/MainWindow.java, src/com/willwinder/universalgcodesender/types/Macro.java, src/com/willwinder/universalgcodesender/uielements/MacroPanel.java, src/com/willwinder/universalgcodesender/uielements/MacroTextField.java, src/com/willwinder/universalgcodesender/utils/Settings.java, src/com/willwinder/universalgcodesender/utils/SettingsFactory.java
Move the macros into a collection.  The idea here is to set us up for having an arbitrary number of macros, rather than just 5.  The macro name is stored in the json, and can be used as the macro button label.  The description is stored, and is displayed as hover text.  Also, I moved the nightly build warning into the settings as well.
The changes in this pull request don't directly contribute much, but are setting the stage for better things to come.
=> Macros are stored in a collection

src/com/willwinder/universalgcodesender/AbstractController.java, src/com/willwinder/universalgcodesender/GrblController.java, src/com/willwinder/universalgcodesender/GrblUtils.java, src/com/willwinder/universalgcodesender/IController.java, src/com/willwinder/universalgcodesender/MainWindow.java, src/com/willwinder/universalgcodesender/TinyGController.java, src/com/willwinder/universalgcodesender/listeners/ControllerListener.java, src/com/willwinder/universalgcodesender/listeners/GrblSettingsListener.java, src/com/willwinder/universalgcodesender/model/GUIBackend.java, src/com/willwinder/universalgcodesender/model/Position.java, src/com/willwinder/universalgcodesender/model/Utils.java, src/com/willwinder/universalgcodesender/pendantui/PendantUI.java, src/com/willwinder/universalgcodesender/types/GrblSettingMessage.java, src/com/willwinder/universalgcodesender/uielements/GrblFirmwareSettingsDialog.java, src/com/willwinder/universalgcodesender/visualizer/VisualizerWindow.java, test/com/willwinder/universalgcodesender/GrblControllerTest.java, test/com/willwinder/universalgcodesender/GrblUtilsTest.java, test/com/willwinder/universalgcodesender/model/GUIBackendTest.java
The machine position window now shows units for the coordinates.  This depends entirely on the grbl settings.  I assume there's something similar in tinyg, but I can't test that.  TinyG behavior should be unchanged.  
The jog units are independent from the display units (setting $13), which is also independent from the parser modal state.  We may want to add a display on the UI somewhere to show how incoming motions commands will be interpreted.
=> Machine status window shows units for current position.  See #314

test/com/willwinder/universalgcodesender/AbstractControllerTest.java, test/com/willwinder/universalgcodesender/BufferedCommunicatorTest.java, test/com/willwinder/universalgcodesender/utils/GcodeStreamTest.java
There were a couple of temp files that fail to be deleted.  The delete failures were causing tests to fail, which in turn prevents the maven package job from completing.
=> Fixing tests to clean up temp files

src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java
If the number is missing or not a number, eat the exception and return NaN.
=> UGS crashes on "G162 X Y F2000" #237

ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/statusline/JogStatusLineService.java
Fixed bug where the jog status line unit wasn't updated and that event for the changed setting was fired before the setting was stored.
=> Fixed bug with the jog status line that didn't get updated

ugs-core/src/com/willwinder/universalgcodesender/uielements/jog/StepSizeSpinnerModel.java, ugs-core/test/com/willwinder/universalgcodesender/uielements/jog/StepSizeSpinnerModelTest.java
By calling getNextValue an event will be fired which will cause a call to the same method again. This will be repeated untill the stack is full. Added a test and rewrote the code so that it won't call getNextValue().
=> #637 fixed stack trace in jog-panel when using GTK-theme

ugs-core/src/com/willwinder/universalgcodesender/MacroHelper.java, ugs-core/src/com/willwinder/universalgcodesender/pendantui/PendantUI.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroActionPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroPanel.java, ugs-core/test/com/willwinder/universalgcodesender/MacroHelperTest.java, ugs-core/test/com/willwinder/universalgcodesender/pendantui/PendantUITest.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroService.java
this matches the behavior for how macros handle embedded semicolon
=> split pendant gCode on semicolon to allow multiple commands in a single request

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/Visualizer2TopComponent.java
Moved the initialization of GLCapabilities so that the application may catch any errors (RPi as an example that doesn't have the required GL-capabilities yet).
Issue #918
=> Moved the initialization of GLCapabilities 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/resources/grbl/error_codes_en_US.csv, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
I dug into the issue #867 and found that the error is caused by a NPE from the lookupCode method that checks the error_codes_en_US.csv:
```java
java.lang.NullPointerException
at com.willwinder.universalgcodesender.GrblController.lookupCode(GrblController.java:133)
at com.willwinder.universalgcodesender.GrblController.rawResponseHandler(GrblController.java:174)
at com.willwinder.universalgcodesender.GrblControllerTest.rawResponseHandlerWithUnknownErrorShouldWriteGenericMessageToConsole(GrblControllerTest.java:1220)
...
```
Normally when an error occur the command is marked as completed using the method `this.commandComplete(processed);`, but instead the error is handled by the try/catch which doesn't complete the command.
```java
else if (GrblUtils.isOkErrorAlarmResponse(response)) {
if …
```
=> Update error codes

ugs-core/src/com/willwinder/universalgcodesender/uielements/actions/ConfigureFirmwareAction.java
Fixed a bug that I introduced that will appear on the UGS Classic where the firmware setting menu is never enabled.
The other actions we have implemented have a pattern where `isEnabled()` is overridden, then in the event-listener it will call `setEnabled(isEnabled())`. This didn't work in Classic for some reason.
=> Firmware settings menu is never enabled in UGS Classic

README.md
People running Java 9 can not start UGS platform stable in #943
=> NetBeans 8.1 with UGS requires Java 1.8

ugs-core/src/com/willwinder/universalgcodesender/BufferedCommunicator.java, ugs-core/test/com/willwinder/universalgcodesender/BufferedCommunicatorTest.java
Possible fix for #759 and #944 - After a soft reset the buffered communicator will clear the paused flag to false. Also added tests to make sure the buffers are cleared.
=> Resume operation after soft reset

ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
This is a fix for #863
If limit switches are triggered with no running commands this error will be shown:
After that a soft reset is required by GRBL before unlocking or homing can be done.
=> Error on no command

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
Handle streaming errors in the `communicatorPausedOnError` callback. Now that the controller is notified directly about communicator errors, the handling can be simplified quite a bit. It seems to work properly.
=> Handle streaming errors in the communicatorPausedOnError callback.

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/HomingAction.java
Fixed a "enable/disable"-bug on homing action where it wouldn't disable when disconnected.
=> Fixed enable/disable-bug on homing action 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/SendStatusPanel.java
Added a stop watch to keep track of the time spent streaming a file. It will pause if the controller is paused due to an error or by the user and continue as soon as the job is resumed. This fixes one of the problems in the issue #989
=> Added a stop watch to keep track of the time spent streaming a file

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/CheckModeAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/GetStateAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/HomingAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PauseAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ResetCoordinatesToZeroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ResetXCoordinateToZeroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ResetYCoordinateToZeroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ResetZCoordinateToZeroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ReturnToZeroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/SoftResetAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/StartAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/StopAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/UnlockAction.java
This is because no event will be fired as the actions are initialized as enabled by default. The actions will also react on all UGS events, we only need them to react on state changes.
=> Fixed problem where actions aren't activated when first connected. 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPI.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/Position.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/WorkCoordinateTextField.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/helpers/MachineStatusFontManager.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java
Added functionality for setting work coordinates requested in #977.
It's also possible to use simple mathematical expressions such as the following:
=> Set work coordinate

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPI.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/WorkCoordinateTextField.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java
It does not prepend the current work position when expression starts with + or -. The operations for * and / doesn't collide with anything so they are still usable. Added the '#' that will be replaced with the current work position.
Examples:
* `# + 10` (adds ten to the current work position
* `* 10` (multiplies the current work position by ten)
* `-10`(sets the current work position to negative ten)
Addresses the issue where negative values can't be set #1004 
Original feature request #977
=> Adjusted the expression handler

ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/BufferedCommunicator.java
This fixes the issue #411. 
Don't keep track of the number of commands sent in the `AbstractController` and don't overwrite the command number in `BufferedCommunicator`. The command numbering are handled by the `GcodeStreamReader`.
All commands handled outside a command stream and queued with  `BufferedCommunicator.queueStringForComm` will get command number -1 which would indicate that it isn't apart of a file stream.
=> Jog commands acts as lines in visualizer

README.md
May I suggest some changes to the readme file. I'm thinking that this page should support the development or the experimental users. Other documentation can be added to the web page.
The majority of downloads looks like they are originating from http://winder.github.io/ and its download page is more extensive then in the readme file. So I think it suffices to link to the releases page.
=> Some adjustments to the readme

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/WorkCoordinateSystem.java, ugs-core/test/com/willwinder/universalgcodesender/GcodePreprocessorUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGUtilsTest.java
Added support for handling gcode states from the responses of the controller. It's also now possible to set and handle work coordinates. 
Further improvements for #1071
A small demo can be found here:
https://www.youtube.com/watch?v=_kmXCvtE1Pc
=> Added support for gcode states and work coordinates

README.md
Just noticed the README is still GRBL specific.  This adds TinyG/g2core to the intro paragraph as well. :smile:
=> Add TinyG/g2core to README.md

ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/test/com/willwinder/universalgcodesender/utils/SettingsTest.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/JogControlTopComponent.java
Activated the new jog module by default. Also activated separate step settings for XY  and Z by default.
If we remove the old module it would have the side effect that old users will have the old jog controller completely removed without having the new activated. So I added a check for when the old module is loaded, it will try to load the new then close it self. 
We need to keep the old module a couple of months to make sure people have transitioned to the new before we can remove it.
Fixes #1089
=> Remove old jog control component

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerStatus.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java
Added feed speed units to the controller status. These are used by the machine status panel to convert the feed speed units to the user preferences.  
When changing units in the jog panel it will now also convert the feed rate settings.
When jogging in TinyG the coordinate units G20/G21 are no longer changed. The coordinates for the jog command is converted from the user preferences unit to the controller units. Fixes/workaround for the issue synthetos/g2#374
Also added the preferred units to the visualiser, addresses the issue #650 and #978 
Fixes #1010
=> Added feed speed units to the machine status panel

pom.xml, ugs-platform/DowelModule/src/main/java/com/willwinder/ugs/platform/dowel/DowelGenerator.kt
Hi!
I just tried to build this project from source, on Ubuntu 18.04 & OpenJDK (`version "10.0.1" 2018-04-17`).
It wasn't one-shot success, but with two tiny changes and disabled tests (`mvn package -DskipTests=true`) it worked.
Please consider merging; this makes the build green for me. I've dropped a single line with an unused Sun-specific import, and raised the Kotlin version in `pom.xml` because of a [compiler bug][•].
[•]: https://youtrack.jetbrains.com/issue/KT-21303
The Kotlin's *internal compiler error* looks like this (if anyone would search it):
```
[INFO] Reactor Summary:
[INFO]
[INFO] ugs-parent ......................................... SUCCESS [  0.185 s]
[INFO] ugs-core ........................................... SUCCESS [  8.535 s]
[INFO] ugs-platform-parent …
```
=> Update Kotlin 1.1.51 → 1.2.30, drop proprietary import

ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java
This wants some testing on multiple platforms, and also left/right handed configuration. Tested so far:
[x] Linux right handed (@carneeki )
[x] Linux left handed (@carneeki )
[ ] MacOS right handed
[ ] MacOS left handed
[ ] Windows right handed
[ ] Windows left handed
Upon clicking with the secondary mouse button, a small popup to configure separate stepping for Z axis appears. While this was not intended in my fix, I suspect it is a useful thing to have, and it does not result in machine movement. Will remove if requested.
=> ignore RMB with regards to LongMouseListener, fixes #1132, fixes #1146

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/src/resources/MessagesBundle_es_ES.properties, ugs-core/src/resources/MessagesBundle_pt_BR.properties, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/AutoLevelPreview.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/AutoLevelerTopComponent.form, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/AutoLevelerTopComponent.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScanner.java
Hello, all right? 
I made some autoleveler corrections that appeared for Min, if you can look at this, maybe I can help you.
Fixes:
-Clean autolever before applying surface leveling.
-Disable function to apply to Gcode when already applied.
-Correction of Probe collection:
-Collect all measurement points.
-Returns values from the job and not from the machine.
-Add checkbox to Autoleveler visible.
-inch scale.
=> Autoleveler fixes

ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeParserTest.java
Jog commands should not change states for feed rates. Added tests to confirm this. Issue #805.
=> Added tests for states. 

ugs-core/src/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ConnectionSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/src/com/willwinder/universalgcodesender/utils/SettingsFactory.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/utils/SettingsTest.java
The option for enabling the state color is broken in platform edition. I propose that we remove that option as I have a hard time seeing the use for it?
The setting "Enable get state color display" gets removed:
The panel gets white but never changes the state text:
Reject this pull request otherwise, and I'll try to fix the settings for the platform edition instead!
=> Remove option for display state color

ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/CommandPanel.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-pendant/pom.xml, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/lifecycle/startup.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ConsoleNotificationService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/JogActionService.java
When an error occurs in the controller an error popup is created. Multiple errors results in multiple popups which doesn't seem user friendly. Also when running a headless instance these popups are created.
I think it's better to log the errors in the console. In NetBeans notifications can also be created which wouldn't interfere with user interactions:
This pull request also replaces the code in MainWindow for the console with the same UI-component used in the platform edition.
=> Error popups replaced with error messages in console

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java
I'm working on my own joystick / joypad jogging plugin for UGS with GRBL, based on the GRBL team's [suggested implementation](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging#joystick-implementation). Adding support for $J jog commands to the jogMachineTo method (analogous to how it was done for jogMachine) lets such a plugin overcome the limited choices of jogging directions available in jogMachine, allowing for a much more satisfying / responsive joypad interface.
=> added GRBL v1.1  jog syntax support to jogMachineTo (G90) jog command

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/GcodeParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/errors/InvalidGrblCommandErrorParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/errors/MovementInMachineCoordinatesErrorParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/Bundle.properties, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/GcodeTemplate.gcode, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/layer.xml
In issue #1108 theres a command G53 which isn't displayed correctly in the visualiser. I realised that this could also lead to other problems if the machine isn't using homing (which happened to me) there would be no known machine coordinate reference point. I wouldn't want to move in machine coordinates, we could at least show a warning in the editor.
=> Added warning for movement in machine coordinates without using homing.

new-module-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml, ugs-core/pom.xml, ugs-platform/DowelModule/pom.xml, ugs-platform/GcodeTools/pom.xml, ugs-platform/ProbeModule/pom.xml, ugs-platform/ugs-platform-plugin-setup-wizard/pom.xml, ugs-platform/ugs-platform-welcome-page/pom.xml
Upgraded libraries that isn't compatible with jdk11.
Fixes #1263 have tested on a clean rpi-installation using the instructions under https://github.com/winder/Universal-G-Code-Sender/wiki/Raspberry-Pi
=> Fixed issue where application can't be compiled jdk11.

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexer.java, ugs-platform/ugs-platform-gcode-editor/src/test/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexerTest.java
Tweaked tests so that unnecessary error messages in tests no longer is printed.
Adjusted lexer for gcode editor to allow a parameter with a space `X 10.0` which seems to be added by some CAM:s.
Discussion in #1214
=> Tweaked tests to prevent unnecessary error messages and updated lexer to allow space in parameter

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/resources/MessagesBundle_en_US.properties
I added a new firmware profile for g2core. We need an message for when connecting with the wrong profile to the g2core hardware.
=> Added error message for when connecting to g2core hardware using the tinyg controller driver

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java
Fixes #1269 
Made the decimal point optional which now makes it possible to parse positions reported like this:
<Run,MPos:50.400,43.200,0.000,WPos:50000,42.600,0.000>
=> Fixes problem where position is reported with an even number.

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodeParser.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeParserUtils.java, ugs-core/src/com/willwinder/universalgcodesender/types/GcodeCommand.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStreamReader.java, ugs-core/src/resources/firmware_config/g2core.json, ugs-core/test/com/willwinder/universalgcodesender/GcodePreprocessorUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeParserTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendPreprocessorTest.java
Fixes #1318
Removed the function in the gcode parsing that removes comments. This should be done by the preprocessor.
=> Do not remove comments by default

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/service/JoystickServiceImpl.java
Do not attempt to close the gamepad connection if it hasn't been initialized.
=> Do not attempt to close the gamepad connection if it hasn't been ininialized.

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/service/JoystickServiceImpl.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ActionRegistrationService.java
Fixes #1410 
Turns out I have the same problem once I fetched the latest code. I was working on another feature and thought I had the latest.
So I first tried using an annotation which will will run a method when starting (@OnStart) which didn't work. Then I tried one that will run once the GUI is showing (@OnShowing) which did work. But I realised that this would require a restart as soon as you add a macro or install plugins. 
So it will now invalidate the action cache if something is created or updated.
=> Now invalidates the action cache if something is created or updated.

ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java
Windows and MacOSX can successfully use JSerialComm but Linux have problems with it and still needs JSSC.
Made JSSC default driver on Linux.
Temporary fix for #1213
=> Now uses JSSC as a default connection driver on Linux

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java
Now handles the version string from GrblHAL. 
Addresses the issue #1468
=> Add basic support for GrblHAL

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ButtonGridPanel.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/ToolboxTopComponent.java
When using the dark theme it won't adjust columns when shrinking the window. Needed to remove the scrollbar.
=> Fixed scaling problems when using dark theme

ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java
This caused problems when loading files while not connected to the machine.
Fixes #1496
=> Removed the CommandLengthProcessor from the default rules.

ugs-platform/pom.xml
Changed the default JRE:s for Windows and RaspberryPi.
Fixes #1493 
Fixes #1505
=> Now using a 32-bit JRE for Windows and JRE8 for raspberry pi.

ugs-platform/pom.xml, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeDataObject.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeFileListener.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java
The GcodeDataObject is not recreated on windows if opening the same file twice. Needed to move the opening code to the SourceMultiViewElement instead and listen to if the TopComponent is opened.
Should fix the issue: #1507
=> Fixed problem with opening files on windows

ugs-platform/ugs-platform-plugin-cloud-storage/src/test/java/com/willwinder/ugs/nbp/S3FileSystemViewTest.java
The test com.willwinder.ugs.nbp.S3FileSystemViewTest.testGetFiles asserts that under the directory "s3:/test-files/" there
are two files. However, the createBucket method has a caching method that saves the bucket with the same name across tests. So if another test like
com.willwinder.ugs.nbp.S3FileSystemViewTest.testUploadDownloadFile calls the method createBucket with the same name
and then puts files under this bucket, it will pollute the cached bucket and the assertion will fail.
=> flakiness in bucket

ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
Tests in com.willwinder.universalgcodesender.GrblControllerTest have assertions that rely on the localization setting being US, and the localization is shared between tests. If a test like com.willwinder.universalgcodesender.i18n.LocalizationTest.loadLocalizationThatDoesExistShouldLoad changes the localization without setting it back, it will pollute that shared state and these tests that run afterwards would fail. This pull request proposes to explicitly set the localization before tests are run as to ensure they do not fail when run after LocalizationTest.loadLocalizationThatDoesExistShouldLoad.
=> Resetting localization before tests

ugs-platform/ugs-platform-plugin-dro/pom.xml, ugs-platform/ugs-platform-plugin-jog/pom.xml, ugs-platform/ugs-platform-plugin-joystick/pom.xml
Fix the problem for running tests during the build of ugs-platform-app.
[INFO] ugs-platform-plugin-dro ............................ SUCCESS [  4.410 s]
[INFO] ugs-platform-app ................................... FAILURE [ 17.721 s]
Failure is caused by the error that occurs because two different modules
that depends from each other have same ugs-core jar in the classpath
and this causes error because the class is loaded from the wrong
classpath. Exact error printed out by the netbeans classloader:
Caused by: java.lang.ClassNotFoundException: Will not load class
com.willwinder.universalgcodesender.model.UnitUtils$Units arbitrarily
from one of
ModuleCL@0[com.willwinder.ugs.platform.ugslib] and
ModuleCL@1[com.willwinder.ugs.platform.plugin.joystick]
starting from SystemClassLoader[133 …
=> Fix ClassNotFoundException classpath error

ugs-pendant/pom.xml
Currently used nodejs v10.15.0 segfaults during the
build on systemcs which have also a newer systemwide
nodejs installed and prevents the build to complete.
Tested that upgrading nodejs to some newer versions like
10.16.3, 10.17.0, 14.16.0 or latest 16.0.0 fixes the
build problem.
Similar error and fix has been reported here:
https://github.com/eirslett/frontend-maven-plugin/issues/826
Fixes https://github.com/winder/Universal-G-Code-Sender/issues/1587
Signed-off-by: Mika Laitio <lamikr@gmail.com>
=> fix nodejs segfault build problem

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeFileListener.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java
Serialization errors prevented the saving of currently
opened project state and prevented the app to remember
if some gcode was open when app was closed.
NotSerializable error that occurs can be tested with following steps
1) start the ugs-platform with command: mvn nbm:run-platform -pl ugs-platform/application
2) open gcode file
3) closes the ugs-platform
4) Errors in console were shown from the serialization errors
5) restart ugs-platform and previously opened gcode should open automatically
Fixes: https://github.com/winder/Universal-G-Code-Sender/issues/1589
Signed-off-by: Mika Laitio <lamikr@gmail.com>
=> fix saving of last opened project state

ugs-core/src/com/willwinder/universalgcodesender/gcode/util/CommandProcessorLoader.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/util/CommandProcessorLoaderTest.java
Add line splitter initialization to processor config.
Requested on google group
https://groups.google.com/g/universal-gcode-sender/c/gnIdXAxEDhw/m/PrNjDiRdAAAJ?utm_medium=email&utm_source=footer
This doesn't add it to the GUI, you'll still need to add it somewhere in the firmware config file. For example on linux that is `~/.ugs/firmware_config/grbl.json`:
```diff
{
"name": "CommandLengthProcessor",
"enabled": true,
"optional": true,
"args": {
"commandLength": 70
}
+     },
+     {
+       "name": "LineSplitter",
+       "enabled": true,
+       "optional": true,
+       "args": {
+         "segmentLengthMM": 1.5
+       }
}
]
}
```
=> Check for line splitter in processor config.

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java
This fixes issue #1341 - If the Grbl controller has a physical button connected to the reset/abort input, and it's pressed while UGS is streaming commands, UGS doesn't properly detect that Grbl has been reset and does not stop streaming, which could lead to a machine crash.
=> fix for issue #1341

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gcode/toolpaths/AbstractToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gcode/toolpaths/SimplePath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gcode/toolpaths/SimplePocket.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gcode/toolpaths/ToolPathUtils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/v1/EntityPathV1.java
When creating a toolpath with multipolygons it would treat it as one geometry and creating a cut path between the geometries. It will now treat each polygon in the multipolygon as separate features.
Also fixed a bug when reading a .ugsd file it would not close the polygon.
=> Designer geometry split

ugs-core/src/com/willwinder/universalgcodesender/uielements/components/GcodeFileTypeFilter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/OpenAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenAction.java
Now remembers the file chooser settings in the current session. This is the best we can do I think as the settings are OS specific and not accessible.
Fixes #1710 and #1749
=> Now remembers the file chooser settings in the current session

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ControllerProcessorSettingsPanel.java, ugs-core/src/resources/firmware_config/g2core.json, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/options/ControllerPanelController.java
Made g2core command length longer and disabled it by default. Also made the options dialog activate the selected controller in the settings by default.
Addresses the issue #1577
=> Changed default controller settings for g2core

pom.xml, ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/ConnectionWatchTimer.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/StatusPollTimer.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/connection/JSerialCommConnection.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerState.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ThreadHelper.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/G2CoreControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeService.java, ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/MachineStatusPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ConnectDisconnectAction.java
When trying to connect to a controller on the wrong port it was no longer possible to disconnect. The user needed to restart the software.
Made it possible to disconnect from a failed connection. Also added a connection watcher to watch if the serial port was closed and clean up the controller resources.
=> Connect/disconnect will now allow to abort a failed connection 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblEsp32Controller.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/types/CommandListener.java, ugs-core/src/com/willwinder/universalgcodesender/types/GcodeCommand.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ControllerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/G2CoreControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblEsp32ControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/SmoothieControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/types/GcodeCommandTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/ControllerUtilsTest.java
I started working on a new controller implementation and found a need for listening to if a command was completed.
This could be done using a `UGSEventListener` and listening for a CommandEvent in the application, but not from the controller. From the controller we have access to the `ControllerLisener` but would require to implement a rather large listener interface.
I propose to add a listener to the GcodeCommand, this would it make it possible to execute a command and wait for it to be completed:
```java
try {
GcodeCommand command = new GcodeCommand("G0 X10 Y10");
ControllerUtils.sendAndWaitForCompletion(controller, command, 1000); // Wait max 1000ms for the command to complete
if (command.isOk()) {
// Do something with the response
}
} catch (RuntimeException e) {
// The command has …
```
=> Added listeners to commands to listen for when it completes.

ugs-core/src/com/willwinder/universalgcodesender/uielements/components/PopupEditor.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OutlineAction.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/LocalizingService.java
* Added a tooltip to the outline action in the visualizer toolbar.
* Made the text auto selected in the coordinate popup editor
Fixes #1843 and #1826
=> Small fixes

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ContinuousJogWorker.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java
This is a fix for issue #1849. I detailed the reasons why the fix is necessary in the issue. With these changes I no longer have unwanted jog movement on log diagonal jogs after the long press is released.
=> fix for issue #1849

ugs-core/src/com/willwinder/universalgcodesender/uielements/UGSSettingsDialog.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ConnectionSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-pendant/src/main/java/com/willwinder/universalgcodesender/pendantui/PendantUI.java, ugs-pendant/src/test/java/com/willwinder/universalgcodesender/pendantui/PendantUITest.java
Added setting for changing the web pendant port.
Fixes #1785
=> Added setting for changing pendant web port.

pom.xml, ugs-platform/ugs-platform-plugin-designer/pom.xml, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/SubtractAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/TraceImageAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/AbstractEntity.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/Entity.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolBox.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/imagetracer/ImageTracerDialog.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/imagetracer/SVGCanvas.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/imagetracer/TraceSettings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/imagetracer/TraceSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/imagetracer/TraceUtils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/svg/SvgReader.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/EntitiesTreeTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsSaveCookie.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/jankovicsandras/imagetracer/ImageTracer.java, ugs-platform/ugs-platform-plugin-designer/src/main/resources/img/trace.svg, ugs-platform/ugs-platform-plugin-designer/src/main/resources/img/trace24.svg, ugs-platform/ugs-platform-plugin-designer/src/main/resources/img/trace32.svg
Added a new feature for tracing bitmaps to vector graphics. Here is a small demo on how to import a image and adjust different settings to get a nice vectorized image:
I am using the class [imagetracerjava](https://github.com/jankovicsandras/imagetracerjava) by András Jankovics (@jankovicsandras)
The settings works as the following:
* **Number of layers** - this will try to separate a number of colors to different layers. The minimum is two. 
* **Color range** - Filters which colors to work with - essentially this will brighten or darken the image, cutting off darker or lighter colors to work with.
* **Color quantization** - the defined number of layers will generate a color palette to use. This value will force near colors to that palette
* **Smooth lines** - If a line segment is jagged …
=> Added a feature for tracing bitmap images

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java
Make sure commands that responds with a status report is also cleared in TinyG-controllers. When resetting the controller it will get the status connecting.
=> Clear status report commands in TinyG

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/connection/ResponseMessageHandler.java, ugs-core/src/com/willwinder/universalgcodesender/model/CNCPoint.java, ugs-core/src/com/willwinder/universalgcodesender/model/Position.java, ugs-core/src/com/willwinder/universalgcodesender/utils/SettingsFactory.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/VisualizerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/visualizer/VisualizerUtilsTest.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/Tool.java
Made an attempt to make GRBL recognize extra coordinates for ABC-axes, adding them as capabilities if the status report contains them.
Here is an example of a grblHAL-controller. It also works with [grbl-mega-5x](https://github.com/fra589/grbl-Mega-5X):
Related issues: #1399, #1068, #1626
=> GRBL controller will now detect if coordinates contains ABC-coordinates and add it as a controller capability

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/DesignerMain.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/selection/SelectionManager.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntitiesTree.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntityCellRenderer.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntityTreeModel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/logic/Controller.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/logic/ControllerEventType.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/EntitiesTreeTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsTopComponent.java
Fixed problem with the entity tree not expanding its rows when starting the designer. Now also closes related top components when the designer is closed.
=> Fixed problem with the entity tree not expanding its rows when starting

ugs-core/src/com/willwinder/universalgcodesender/utils/ThreadHelper.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsTopComponent.java, ugs-platform/ugs-platform-plugin-filebrowser/src/main/java/com/willwinder/ugs/nbp/filebrowser/FileBrowserDialog.java, ugs-platform/ugs-platform-plugin-filebrowser/src/main/java/com/willwinder/ugs/nbp/filebrowser/FileTableModel.java
Added a feature for renaming files on the controller. As there isn't such operation on the controller, we will download the file and upload it with the new name.
=> Added feature for file rename

ugs-core/src/com/willwinder/universalgcodesender/types/Macro.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/src/com/willwinder/universalgcodesender/utils/SettingsFactory.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ThreadHelper.java, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/Bundle.properties, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacrosTopComponent.java
Added a UUID to macros in order to identify them uniquely. Previously the name was used to register the macro action which is then stored with that file name. The name may contain illegal characters for the file system which would break any macro shortcut. 
The name of the macro action was not updated which is now also fixed.
Fixes #1901 
Fixes #1862
Fixes #1827
=> Fixed macro shortcuts

ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/Position.java
Update FluidNC controller to invoke probeCoordinates on listeners on PRB messages.
=> Add FluidNC probe support

ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeParserUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/FirmwareUtils.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeFileWriter.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStreamReader.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStreamWriter.java, ugs-core/src/com/willwinder/universalgcodesender/utils/SettingsFactory.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendPreprocessorTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/GcodeStreamTest.java, ugs-platform/DowelModule/src/main/java/com/willwinder/ugs/platform/dowel/DowelTopComponent.java, ugs-platform/GcodeTools/src/main/java/com/willwinder/ugp/tools/GcodeTilerTopComponent.java
Now assumes that gcode files are in UTF-8.
Settings, macros and other files written by UGS will now be in UTF-8.
Possible fix for #2078 and #2011
=> Fix file encoding problems

ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerListener.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/events/FileStateEvent.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
Communicator state changes will no longer be dispatched as they aren't used by the UI. Also removed the boolean for notifying if the file send successful as it was always true.
This is a part of the work for introducing a new console plugin.
=> Removed the event for communicator state and removed unused code

ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-platform/pom.xml, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/AbstractDesignAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ExportGcodeAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/MoveAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/NewAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/OpenAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/RedoAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/RotateAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolZoomAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/UndoAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/controls/MoveControl.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/controls/ResizeControl.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/controls/RotationControl.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntitiesTree.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntityCellRenderer.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/EntitiesTreeTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/PlatformUtils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsOpenSupport.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsSaveCookie.java
This caused it to create duplicates of the service somehow. Created its own singleton instead. Also now loads a new gcode model when the design is saved instead of when the design is updated.
=> Do not use CentralLookup to look up the Controller-instance

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/SelectNextAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/SelectPreviousAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/MainMenu.java
Add actions for selecting previous and next entity in the designer which can be assigned a keymap or assigned to a gamepad.
=> Add actions for selecting previous and next entity in the designer

ugs-core/src/com/willwinder/universalgcodesender/gcode/processors/CommandProcessorList.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToggleHidden.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolDrawCircleAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolImportAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolSelectAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolBox.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/clipart/InsertClipartDialog.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java
Grouped all "creator" actions to make room for other actions in the toolbar.
The action for toggling visibility will now also toggle the icon and title based on the hidden/visible state. 
Attempt to fix jog controller not being enabled on certain platforms
=> Small adjustments in the Designer

ugs-core/src/com/willwinder/universalgcodesender/gcode/processors/CommandProcessorList.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ugs-platform-plugin-cloud-storage/src/main/java/com/willwinder/ugs/nbp/CloudStorageOpenAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToggleHidden.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolDrawCircleAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolImportAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolSelectAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolBox.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/clipart/InsertClipartDialog.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenFileAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenRecentAction.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/LocalizingService.java, ugs-platform/ugs-platform-welcome-page/src/main/java/com/willwinder/ugp/welcome/RecentWorkTab.java
Add menu for opening recent files
Fixes #1724
=> Add menu for opening recent files

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtils.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/CommandTextArea.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ControllerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/ControllerUtilsTest.java, ugs-platform/ugs-platform-plugin-console/src/main/java/com/willwinder/ugs/nbp/console/ConsolePanel.java, ugs-platform/ugs-platform-plugin-filebrowser/src/main/java/com/willwinder/ugs/nbp/filebrowser/actions/OpenFileBrowserAction.java
Made a couple of usability changes to the FluidNC implementation:
* When stopping a running GCode program it will no longer fully reset the controller
* When initializing and it starts in Alarm or Hold state it will now do a quick check if it is finite and requires a reset
* Made the command text area active on alarms to be able to reconfigure the controller
* Made the console window focusable again to be able to copy text
* Made the file browser openable on alarm state
=> FluidNC usability fixes

ugs-core/src/com/willwinder/universalgcodesender/communicator/event/AsyncCommunicatorEventDispatcher.java, ugs-core/test/com/willwinder/universalgcodesender/communicator/event/AsyncCommunicatorEventDispatcherTest.java
There were scenarios where two worker threads created. This could make the queue processing out of sync. This patch should ensure that there is only one worker thread available.
=> Attempt to fix concurrency problem in event dispatcher

pom.xml, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntityGroup.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Rectangle.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/svg/SvgReader.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/entities/cuttable/PathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/entities/cuttable/RectangleTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/svg/SvgReaderTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/resources/1x1inch.svg, ugs-platform/ugs-platform-plugin-designer/src/test/resources/20x20mm.svg, ugs-platform/ugs-platform-plugin-designer/src/test/resources/lines.svg
* Import SVG:s synchronously and applies the units to the scale transform.
* Shapes with no width or height will be taken into account in a group.
Fixes #2055
Fixes #2056
=> Fixes for SVG import

ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPI.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/events/FileState.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/toolbars/SendStatusLine.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-platform/ugs-platform-gcode-editor/pom.xml, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/EditorUtils.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/NewGcodeAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/example.gcode, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/new.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/new24.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/new32.svg, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/NewDesignAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsDataObject.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsSaveCookie.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java
Previously when creating a new design you needed to type the file name first. This has now been fixed so that you'll get a unnamed file that you need to name when you save.
There is now also an action for creating new gcode files.
When closing a gcode or design file, the gcode is cleared from the visualizer.
Fixes: #2140
Fixes: #2120
Fixes: #2057
=> New design and gcode actions

ugs-core/src/com/willwinder/universalgcodesender/MacroHelper.java, ugs-core/src/com/willwinder/universalgcodesender/services/KeyboardService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ProgramAction.java
Keypress macros will now properly send modifiers keys such as SHIFT, ALT, CTRL and META
=> Fixed keypress macros

pom.xml, ugs-core/pom.xml
=> Update jogl / gluegen to 2.4.0

ugs-core/src/com/willwinder/universalgcodesender/Capabilities.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java
A legacy grbl status seems to send alarm state as `<Alarm>`. The status parser expected a comma after the state string.
Potential fix for #2185
=> Fix parsing of alarm state in legacy grbl status format

ugs-core/src/com/willwinder/universalgcodesender/actions/ConfigureFirmwareAction.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/SmoothieCommandCreator.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/SmoothieUtils.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/commands/GetVersionCommand.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/commands/SmoothieCommand.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ControllerSettings.java
Force smoothieware to use single step mode. 
Add a specific command creator.
=> Fix for smoothie

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java
Now only parses if the line starts with "ok" or "error"
=> Fixed problem with responses containing "error" not being an error in FluidNC

ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/RoundedPanel.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/VisualizerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtilsTest.java
When loading a gcode model in inches it will use the wrong units for the arc segment length.
=> Fix problem with the arc expander not working with inches

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeParameters.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeTopComponent.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/actions/AbstractProbeAction.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/renderable/ProbePreviewManager.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ui/SettingsPanel.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/AutoLevelerTopComponent.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScanner.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/ui/AutoLevelerPanel.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/GcodeRenderer.java
Fixes for a couple of bugs on probing:
* Fixed problem with setting enable which can't be done in the event thread causing exceptions
* Added a tooltip that describes how the retract amount works
* Shows/hides the probing/autoleveling preview when the component is shown
* Fixed the wrong mapping of X -> Y value in autoleveler
* Fixed problem with equals matching doubles, lowered the precision.
* Fixed problem with concurrent updates to list of renderables
=> Bugfixes on probing

ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScanner.java
When starting the autoleveler it will make sure to pull the spindle/probe to the max probe height before moving to the XY start position. There were times were I would scratch the surface of the area I was probing.
After the job is finished it will go to the max height and go back to start position.
Also fixed bug where if the GRBL board was set to report in inches the autoleveling wouldn't work.
=> Autoleveler safe retract

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/MachineBoundries.java
It will now treat the machine boundaries using the default grbl settings where the machine is working in negative space.
=> Fixed problem with machine boundries being inverted

ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ui/SettingsPanel.java
If the previous probe settings contains lower values than allowed use the lowest value instead of throwing an exception.
Also lowered the minimum feed rate from 1 to 0.1 which makes more sense when working in imperial units.
=> Fixed problem when trying to load existing probe settings

ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeService.java, ugs-platform/ProbeModule/src/test/java/com/willwinder/ugs/platform/probe/ProbeServiceTest.java
When starting the probe of Y it would move it too far on the X axis using the distance setting. It should instead move to the origin X (0).
Possible fix for #2287
=> Fixed X travel distance in XYZ probing

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexer.java, ugs-platform/ugs-platform-gcode-editor/src/test/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexerTest.java
Gcode parser can not parse multiple white spaces and tabs between parameter and value.
Fixes #2258
=> Gcode parser now allows multiple spaces and tabs

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeTopComponent.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/InsertPositionAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/RunFromAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position24.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position32.svg, ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/ui/BindActionButton.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/LocalizingService.java
Make it possible to map edit actions such as "Insert position" to gamepads
=> Make edit actions mappable to gamepad

ugs-core/src/com/willwinder/universalgcodesender/firmware/grbl/GrblVersion.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/grbl/commands/GetBuildInfoCommand.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/grbl/GrblVersionTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/grbl/commands/GetBuildInfoCommandTest.java
GRBL version 0.9 and earlier does not print the same output to the $I command.
This will fix that so that the version number is properly parsed.
=> Fixed problems with legacy GRBL version strings

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerState.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerStatus.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/MachineStatusPanel.java
Before this fix, it would only update the pin status when there was an override status. This made the pin reporting very slow to show up in the UI. With this fix the pin status is almost immidiate.
Also added a new state for tool change that is present in grblHAL, I have no way of testing it but it should at least not bork the program.
=> Display the pin status immediately

ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java
=> Added possibility to divide step size to 0.001

ugs-platform/application/pom.xml, ugs-platform/pom.xml
Rolled back to NetBeans 18.0 as there was problems with menus on aarch64. 
Fixed link to aarch64 JRE.
=> Fixes for Raspberry PI 64-bit

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/AbstractEntity.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntityGroup.java
When typing 0.01 in the width or height box the value will become 0 once which is not allowed.
=> Fixed problem with resizing entities when typing zero as width or height

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeDataObject.java
Registers an open cookie that can be used for opening the file when not using the editor.
Possible fix for #2299
=> Fix problem with opening same file multiple times

ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ContinuousActionExecutor.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ContinuousActionShortcutListener.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/JogActionService.java, ugs-platform/ugs-platform-ugscore/src/test/java/com/willwinder/ugs/nbp/core/services/ContinuousActionExecutorTest.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ActionRegistrationService.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ShortcutService.java
=> Deactivate continuous jogging when a key is released

ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/DetectEchoCommand.java
Added a detection if echo mode is active and will only try to disable if it is.
This will prevent the echo disable command to be sent on channels that doesn't support them on FluidNC.
=> Added a detection if echo mode is active on FluidNC

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ChangeFontAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ChangeTextAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/MoveAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ResizeAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/RotateAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/controls/ResizeUtils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Text.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/MultiplyDialog.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/tree/EntityCellRenderer.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/AbstractToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/DrillCenterToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/model/Settings.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/model/SettingsTest.java
* Now only does one pass if the start and target depth are the same
* Added undoable actions for the shape settings
This should fix most cases reported in #2412
This fixes problem with multiple passes reported in #2411
=> Fixes to the designer

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/Code.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeParserUtils.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/util/GcodeParserUtilsTest.java
UGS parser expects G38 to have an axis parameter. However, if the controller is in a G38 modal state and a gcode parser state command is issued these commands can't be applied to the gcode state:
```
[GC:G38.2 G54 G17 G21 G90 G94 M5 M9 T0 F100 S0]
```
With this fix, the internal parser will not make it mandatory to have an axis to a probe command, leaving the command validation to the controller.
Fix for #2386
=> Bugfix for handling gcode state G38

pom.xml, ugs-core/src/com/willwinder/universalgcodesender/communicator/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/test/com/willwinder/universalgcodesender/communicator/BufferedCommunicatorTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java
I introduced a problem when a connection could not be established properly the first time.
If the user tried to connect again a second time it would fail. 
It should now properly clear the previous connection.
=> Properly clean up a partially established connection

ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/components/ConnectionPanel.java
This PR adds a combo box for selecting the Driver in the Connection setup wizard.
Fixes #2425. 
To do:
=> Add Driver selector to Connection setup wizard

ugs-core/src/com/willwinder/universalgcodesender/utils/SimpleGcodeStreamWriter.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/MeshLevelManager.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/Utils.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/actions/ExportGcodeAction.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/ui/AutoLevelerToolbar.java, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export.svg, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export32.svg, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export32_dark.svg, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export32_disabled_dark.svg, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export_dark.svg, ugs-platform/ugs-platform-surfacescanner/src/main/resources/com/willwinder/ugs/platform/surfacescanner/icons/export_disabled_dark.svg
Added the possibility to export the autoleveled gcode using the export button:
=> Add possibility to export the autoleveled gcode

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/FileFilterService.java
This is an attempt to fix the problem with the file chooser dialog listing empty directories on MacOSX.
=> Attempt to fix file chooser dialog on MacOSX

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerInitializerTest.java
=> Attempt connection to GRBL for ten seconds instead of three

ugs-core/src/com/willwinder/universalgcodesender/types/Macro.java, ugs-core/src/com/willwinder/universalgcodesender/types/MacroVersion.java, ugs-pendant/src/main/java/com/willwinder/universalgcodesender/pendantui/v1/model/Macro.java
As discussed in #2404 this change will allow macro versioning for backwards compatibility.
When reading a macro from settings, it will default to `version = MacroVersion.V1` if there is no version associated to the macro.
=> added macro versioning

ugs-core/src/com/willwinder/universalgcodesender/MacroHelper.java, ugs-core/src/com/willwinder/universalgcodesender/RequestFocusListener.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/RequestFocusListener.java
Resolves: https://github.com/winder/Universal-G-Code-Sender/issues/2473
I've not touched Java in many years so this solution is taken mostly from here: 
https://tips4java.wordpress.com/2010/03/14/dialog-focus/
It seems to behave differently on different platforms. HierarchyListener was the only listener that worked on Linux.
=> fix: Set focus to first field in macro popup

pom.xml, ugs-cli/src/main/java/com/willwinder/ugs/cli/BackendInitializerHelper.java, ugs-cli/src/main/java/com/willwinder/ugs/cli/ProgressBarPrinter.java, ugs-cli/src/main/java/com/willwinder/ugs/cli/TerminalClient.java
Fixed a problem with cli which will only require a connection if homing or a file should be runned
=> Fix cli so that it does not require a connection

pom.xml, ugs-pendant/src/main/java/com/willwinder/universalgcodesender/pendantui/JettyHttpContainerFactory.java, ugs-pendant/src/main/java/com/willwinder/universalgcodesender/pendantui/PendantUI.java
When the shade plugin copies the classes from jersey lib it will by default use the version which throws an compatibility error. As a workaround I have copied the factory class.
=> Bugfix pendant

ugs-core/src/com/willwinder/universalgcodesender/firmware/DefaultFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/IFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/SpeedMap.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetFirmwareSettingsCommand.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/grbl/GrblFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/tinyg/TinyGFirmwareSettings.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/SpeedMapTest.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntitySetting.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsModel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/GcodePath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/Segment.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/AbstractToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/LaserFillToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/LaserOutlineToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/model/Settings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsAdapter.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/LaserOutlinePathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPathTest.java
The max spindle speed is now read from the controller and can be applied as a percentage on both milling and laser operations (it was previously stored on the project).
The feed rate can now also be set per shape.
The max spindle speed will by default be read from the controller, but there is an option to set it manually by unchecking the "Detect max spindle speed":
=> Reads the max spindle speed from the controller 

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/controls/GridControl.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/Drawing.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/DrawingContainer.java
=> Made it possible to design in negative space

ugs-core/src/com/willwinder/universalgcodesender/connection/JSerialCommConnection.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java
Attempt to warn user if permissions to device is missing. 
Prevent the user from starting a stream twice when the machine is waiting for G4 dwell command
=> Minor fixes

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/Visualizer2TopComponent.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/GcodeRenderer.java
=> Load the gcode model when opening the visualizer

ugs-core/src/com/willwinder/universalgcodesender/GrblControllerInitializer.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
It requires a small pause between querying the status and fetching the build information.
=> Fixed connection problem with GRBL_ESP32 in wifi mode

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblControllerInitializer.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/mockobjects/MockGrblCommunicator.java
Cancels the current stream if the controller is reset and prevent the initialization to trigger twice if already started.
=> Fixes for controller resets

ugs-pendant/src/main/webapp/src/store/socketMiddleware.ts, ugs-platform/application/nb-configuration.xml
`mvn install` gave an error for ugs-pendant.
```
[INFO] --- frontend-maven-plugin:1.12.0:npm (build prod) @ ugs-pendant ---
[INFO] Running 'npm run build' in /home/erhannis/clones/Universal-G-Code-Sender/ugs-pendant/src/main/webapp
[INFO] 
[INFO] > webapp2@0.0.0 build
[INFO] > tsc && vite build
[INFO] 
[INFO] src/store/socketMiddleware.ts(25,3): error TS2322: Type 'Timeout' is not assignable to type 'number'.
```
I don't know why nobody else has had this problem, but replacing type `number` with `NodeJS.Timeout` made the error go away.
=> Pendant timeout class mismatch

ugs-platform/ugs-platform-visualizer/pom.xml, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/jogl/NewtVisualizationPanel.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/jogl/VisualizationPanel.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/Grid.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/OrientationCube.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/Plane.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shader/PlainShader.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shader/Shader.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/GcodeRenderer.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/VertexObjectRenderable.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/utils/RenderableUtils.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/utils/ShaderLoader.java, ugs-platform/ugs-platform-visualizer/src/main/resources/shaders/plain.vert.glsl
I have replaced the old orientation cube with a variant created using [JCSG](https://github.com/NeuronRobotics/JCSG).
By using OpenGL:s Vertex Buffer Objects the performance is better.
The default method for rendering is by using JOGL:s AWT binding. This has the downside that multisampling is not possible. The rendering of the cube will therefore look something like this:
With the new NEWT rendering it will look a bit better:
=> Orientation cube using JCSG

ugs-core/src/com/willwinder/universalgcodesender/uielements/FileDialogBase.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/FileOpenDialog.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/Utils.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/actions/OpenScannedSurfaceAction.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/actions/TogglePreviewAction.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/io/XyzFileFilter.java, ugs-platform/ugs-platform-surfacescanner/src/test/java/com/willwinder/ugs/platform/surfacescanner/UtilsTest.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OpenAction.java
=> Fix problem with opening XYZ files containing negative positions

ugs-core/src/com/willwinder/universalgcodesender/model/PartialPosition.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScanner.java, ugs-platform/ugs-platform-surfacescanner/src/test/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScannerTest.java
Fixes the issue with default settings causing the probing to send ABC-axes
Discussed in #2679
=> Clear ABC axes when probing

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtilsTest.java
When connecting to older 8-bit controllers with GRBL it will always reset it. This does not happen on some newer 32-bit ones. If the controller was left in "Check-mode" some commands will not work during initialization. 
This fix will reset the controller to exit the check mode if this happens.
Fixes #2696
=> Resets the controller when initializing in check state

ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeParserException.java, ugs-core/src/com/willwinder/universalgcodesender/utils/MathUtils.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/GcodeViewParse.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/VisualizerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/MathUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/visualizer/VisualizerUtilsTest.java
Fixes a problem where a program like this could not be loaded:
```
G17 G21 G90 G94 G54 M0 M5 M9
G0 X10  Y10.0   F8.0
G02 X20 Y0      R-10
```
NCViewer displays it like this:
There were two problems. A check was in place to prevent negative radius values which was removed. But we also needed to handle the special case to invert the angle when there is a negative radius. Of there these fixes it now displays correctly with:
Also prevent spamming error dialogs when loading gcode with multiple errors. Removed unused parameter for spindle speed.
Relates to #2710
=> Fix problem with arcs with negative radius

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java
When connecting to a GRBL controller which is in DOOR state it will not accept any other commands which will prevent it from intializing. With older hardware it will always reset on connection, but newer 32-bit boards will not which will not make it possible to connect.
Added a reset upon connecting if the controller is in DOOR-state.
See discussion in #2737
=> Restart controller when in DOOR-state

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java
- Wrapped calls to unsafe methods with SwingUtilities.invokeLater
- Fixed issues causing:  https://github.com/winder/Universal-G-Code-Sender/issues/2746#issue-2988180880
=> Force calls which will update the UI to execute in the swing thread.

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntitySetting.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Cuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CuttableEntitySettings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Group.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/FieldEventDispatcher.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsModel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java
- Added a new Checkbox to designers Selection Settings Panel to allow user to include / exclude a shape from being exported to gcode.
This should fix: https://github.com/winder/Universal-G-Code-Sender/issues/2824
=> Added ability to remove entity from generated g-code without loosing cut settings

ugs-core/src/com/willwinder/universalgcodesender/uielements/TextFieldUnit.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CuttableEntitySettings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsPanel.java
Hi, I would suggest adding add a text field for the laser power (spindle speed) to allow entering low values (e.g. 4%) for laser engraving: 
https://github.com/user-attachments/assets/0f8e2966-854d-4c9d-be49-2652b581796e
To show this, I made a PoC but you may want to do this differently.
As far as I understood, there are two "issues"
1. the `SPINDLE_SPEED` entity property seems to be an Integer `{1..100}` while the `UnitSpinner` outputs a Double
- my workaround was to add code in `setEntitySetting` to round this Double to an Integer
2. the `PERCENT` type in the `TextFieldUnit` is additionally muliplied and divided by 100
- my workaround was to add a `PERCENT1` unit which circuments these code pathes
I haven't tested this yet on my cnc but what do you think - would it be possible to …
=> adding a text field for the spindle speed in the 'Cut settings' dialog
