winder/Universal-G-Code-Sender

src/com/willwinder/universalgcodesender/MainWindow.java
=> Validate step size before send movement command in manual mode

src/com/willwinder/universalgcodesender/MainWindow.form, src/com/willwinder/universalgcodesender/MainWindow.java, src/resources/MessagesBundle.properties
=> Move jog panel to left, making room for macro buttons

src/com/willwinder/universalgcodesender/MainWindow.form, src/com/willwinder/universalgcodesender/MainWindow.java, src/com/willwinder/universalgcodesender/uielements/MacroActionPanel.java, src/com/willwinder/universalgcodesender/uielements/MacroDescriptionField.java, src/com/willwinder/universalgcodesender/uielements/MacroNameField.java, src/com/willwinder/universalgcodesender/utils/Settings.java, src/resources/MessagesBundle.properties
Add macro buttons to the machine control tab.  Macros tab is now mainly a macro edit page.  Added fields for name and description.
Macros tab is a bit ugly, but functional.
=> Macros on machine control

src/com/willwinder/universalgcodesender/MainWindow.form, src/com/willwinder/universalgcodesender/MainWindow.java
Screen works at 1024x600.  Resolves #374
=> Put the jog panel back where it was.  

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/types/GcodeCommand.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/GrblFirmwareSettingsDialog.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/SendStatusPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/SettingsFactory.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/options/SenderOptionsPanel.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ActionRegistrationService.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1192 - String literals should not be duplicated
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1192
Please let me know if you have any questions.
M-Ezzat
=> squid:S1192 - String literals should not be duplicated

ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/GcodeTable.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/GrblFirmwareSettingsDialog.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/VisualizerCanvas.java, ugs-core/src/third_party/PersistentVector.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/console/SerialConsoleTopComponent.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/JogService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/toolbars/SerialPortToolbarBox.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/GcodeRenderer.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/util/GcodeModel.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/util/Grid.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2039 - Member variable visibility should be specified
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
Please let me know if you have any questions.
M-Ezzat
=> squid:S2039 - Member variable visibility should be specified

ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/ExperimentalWindow.java, ugs-core/src/com/willwinder/universalgcodesender/GrblSimulator.java, ugs-core/src/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodeCommandBuffer.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodeParser.java, ugs-core/src/com/willwinder/universalgcodesender/i18n/Language.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/GrblSettingsListener.java, ugs-core/src/com/willwinder/universalgcodesender/model/SerialWriter.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/GrblFirmwareSettingsDialog.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/MacroActionPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/TableCellListener.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/GcodeViewParse.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/LineSegment.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/VisualizerCanvas.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/type/GcodeVisualElement.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/toolbars/SerialPortToolbarBox.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/options/OptionTable.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/GcodeRenderer.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
Please let me know if you have any questions.
M-Ezzat
=> pmd:ImmutableField - Immutable Field

ugs-core/src/com/willwinder/universalgcodesender/uielements/MacroActionPanel.java
=> MacroActionPanel fill columns first

pom.xml, ugs-core/pom.xml, ugs-core/src/com/willwinder/universalgcodesender/i18n/Localization.java, ugs-platform/pom.xml, ugs-platform/ugs-platform-gcode-editor/pom.xml, ugs-platform/ugs-platform-plugin-workflow/pom.xml, ugs-platform/ugs-platform-ugscore/pom.xml, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/JogActionService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroService.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/RunActionService.java, ugs-platform/ugs-platform-ugslib/pom.xml, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ActionRegistrationService.java, ugs-platform/ugs-platform-visualizer/pom.xml
Fixes the error message when opening the toolbar customization tool after the locale has been switched. Issue #619
The identifiers unfortunately needs the addition of a magic string. Decide if you think this is the right solution. :)
This could maybe be solved by using the action class name. But this requires that the action only has one usage, as opposed to OverrideAction for example which has many actions built into it.
=> Added unique identifiers for all actions, issue #619

ugs-platform/branding/src/main/resources/com/willwinder/branding/Bundle.properties, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/platform/gcode/editor/Bundle.properties, ugs-platform/ugs-platform-plugin-workflow/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-plugin-workflow/src/main/resources/com/willwinder/ugs/platform/plugin/workflow/Bundle.properties, ugs-platform/ugs-platform-ugscore/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-ugscore/src/main/resources/com/willwinder/ugs/nbp/core/Bundle.properties, ugs-platform/ugs-platform-ugslib/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-ugslib/src/main/resources/com/willwinder/ugs/nbp/lib/Bundle.properties, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/Bundle_1.properties, ugs-platform/ugs-platform-visualizer/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-visualizer/src/main/resources/com/willwinder/ugs/platform/visualizer/Bundle.properties
Added more information to plugin manifests for the plugin configuration tool:
=> Added more information to the plugin manifests

ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
I wrote two tests that confirms that the go-to-home button goes to Z0 first if the work Z-position is negative. This could help understanding the issue #625?
=> #625 I wrote two tests that confirms that the go-to-home button goes to Z0 first

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/src/resources/MessagesBundle_sv_SE.properties, ugs-platform/ugs-platform-ugscore/pom.xml, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/lifecycle/startup.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/SettingsChangedNotificationService.java
When the language settings are changed the platform needs to be restarted. With this PR these changes will notify the user about a platform restart.
=> Added a notification for restart when the language is changed.

ugs-core/src/com/willwinder/universalgcodesender/i18n/Localization.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroPanel.java
Should fix a problem where the macro buttons aren't enabled default when opening the options panel
=> #636 fixes problem with non enabled macros button in options-panel

ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java
I believe this caused the failed build
=> Fixed missing retractHeight field in settings

run_platform.sh, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/RoundedPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java
Simple change to practice setting up development and doing a pull request.
This change prevents the program from running when the build fails.
=> Join commands with && so if build fails, program is not launched.

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java
There are four paths through this code. I tested 2 of them. Not sure what conditions for which `feedSpeed` is null. I don't have spindle control. So I tested `feedSpeed` not null and `spindleSpeed` null.
issue #812
=> Fix NPE in machine state feed/spindle speed display.

ugs-core/src/com/willwinder/universalgcodesender/uielements/jog/JogPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroActionPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ActionButtonPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ConnectionSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ControllerProcessorSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/SendStatusPanel.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/AutoLevelerSettingsPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/windows/StateTopComponent.java
Probably a good idea to run both Classic and Platform and resize stuff, see if I made anything worse.
issue #826
=> Stretch in X direction but not Y.

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java
Earlier changes I made to the DRO don't play well with various Look and Feel "themes".
Derive color of sub panels from parent container.
Preserve default text color.
Tweak size of machine position font to improve rendering.
=> DRO Panel visual improvements

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java
Made the axis reset buttons a little smaller so overall the smallest DRO arrangement should be pretty close to previous version (before I got involved). Had a complaint that it was too big.
=> DRO, tweak axis zero button.

ugs-platform/branding/src/main/nbm-branding/core/core.jar/org/netbeans/core/ui/Bundle.properties
Corrected the icon credits after feedback from @dastultz in issue #823
=> Corrected the icon credits

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPIReadOnly.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/Visualizer2TopComponent.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/VisualizerPopupMenu.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/actions/JogToHereAction.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/actions/MoveCameraAction.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/GcodeRenderer.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/RenderableCheckBox.java, ugs-platform/ugs-platform-visualizer/src/test/java/com/willwinder/ugs/nbm/visualizer/VisualizerTestMain.java
Fixes for the issue: #737
* Moved the popup menu items for enabling features to a sub menu
* Added submenu with view presets
* Fixed a potential memory leak for listeners that aren't unregistered when the window is closed
* Sorts the popup menu items using their titles instead of priority
* Fixed a couple of Codacy warnings
=> Usability improvements in the visualiser

ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/test/com/willwinder/universalgcodesender/utils/SettingsTest.java
Changed the default baud-rate as mentioned in issue #871 and fixed a couple of Codacy-warnings.
=> Changed the default baud rate in the settings

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/HomingAction.java, ugs-platform/ugs-platform-ugscore/src/main/resources/com/willwinder/ugs/nbp/core/layer.xml
Added the home button as a the default action to the toolbar as specified in #823
=> Added the home button as a default action to the toolbar

ugs-core/src/com/willwinder/universalgcodesender/AbstractCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/BufferedCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/BufferedCommunicatorTest.java
The raw command streams aren't used so I had it removed. I also added a test for checking the ordering of the command processing of "command stream" and the "command string" in BufferedCommunicator.
=> Removed raw command streams

ugs-core/src/com/willwinder/universalgcodesender/i18n/Localization.java, ugs-core/test/com/willwinder/universalgcodesender/i18n/LocalizationTest.java
=> Added a check if the resource bundle could be loaded or default to english

ISSUE_TEMPLATE.md
A suggestion for a issue template as described in #865
=> An issue template

ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanelListener.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java
I forgotten to add events and listeners for the step size and and feed rate spinners.
=> Forgot to add events in new jog panel

ISSUE_TEMPLATE.md
Removed check boxes as they will appear as tasks in Github. The fields are now plain text.
=> Removed check boxes as they will appear as tasks in Github

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/SendStatusPanel.java
Fixed problem with panel layout where it couldn't be shrunken once made wider (issue #989)
=> Fixed problem with panel width

ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/actions/UseSeparateStepSizeAction.java
=> Fixes problem where menu option isn't enabled when connecting.

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/StartAction.java
Fixed bug that I introduced where start action isn't activated when loading the file for the first time.
=> Fixed bug where start action isn't activated 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPIReadOnly.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/SendStatusPanel.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java
Fixes the issues with wrong statistics in the send status panel, issue #989 
Will now wait till the controller is idle before sending an event that the file stream is completed, issue #993
=> Fixed a couple of issues in send stats

ugs-core/src/com/willwinder/universalgcodesender/firmware/DefaultFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/GrblFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/IFirmwareSettings.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelSoftLimits.java
Added jog controllers so that one can jog the machine to the position that is going to be the soft limit:
=> Improved the setup wizard so that one can jog to test the soft limits

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
this is basically "#1032 by zuzu59" + "update tests" - "delete trailing whitespaces".
=> In the JOG module, the feed speed is not taken into account (bug)

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java
=> Fixed bug where state wasn't updated

README.md
Forgot to include these in the previous PR.
=> Add links to TinyG and g2core GitHub repos

ugs-core/src/com/willwinder/universalgcodesender/uielements/jog/StepSizeSpinnerModel.java, ugs-core/test/com/willwinder/universalgcodesender/uielements/jog/StepSizeSpinnerModelTest.java
Made a small adjustment to make it possible to set jog feed rates to more than 1000.
=> Fixed so that the feed rate and step sizes can be set to more than 1000

ugs-core/src/com/willwinder/universalgcodesender/GrblCapabilitiesConstants.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/OverridesPanel.java
The overrides panel will now check if the controller has override capabilities and will in that case activate the buttons.
=> Now uses the overrides capabilities

ugs-core/src/com/willwinder/universalgcodesender/TinyGCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerStatus.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGUtilsTest.java
Added overrides to tinyg/g2core controllers. Fixes #1095 
Also fixes parsing of positions that begins with a zero: 0.111 which couldn't be interpreted.
=> Added overrides to tinyg/g2core controllers

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/UnitUtils.java, ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/PositionTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/SettingsTest.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/NavigationButtons.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/WizardUtils.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/statusline/JogStatusLineService.java
Fixes part of #1010.
When switching between inches and mm in jog panel it will now convert the current value to that unit. The feed rate requires a bit more thought as I'm not sure how those settings work...
I changed it so that the controller returns the coordinates in its own units. The consumers of these coordinate data are now required to handle how it should be presented. The machine panels now converts to the preferred units.
Also made small refactorings and removed deprecated code.
=> Feature - convert step size

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeService.java, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeTopComponent.java, ugs-platform/ProbeModule/src/test/java/com/willwinder/ugs/platform/probe/ProbeServiceTest.java
Hi Will,
I encountered some issues when trying to probe in inch units, so I thought I see if I could fix it. The tests pass, and I did some manual testing on my machine, and everything appears to be working correctly (in inch and mm units).
I'm new to the codebase (and actually to github as well), though I've been doing java development for a long time. Let me know what you think.
Thanks,
Jon
=> Fixed issues with ProbeModule for inch units

ugs-core/src/com/willwinder/universalgcodesender/uielements/jog/StepSizeSpinner.java
Make sure the spinner component issues change events every time the text field is modified.
=> Fixes #1185 - make sure the spinner component issues change events

ugs-core/src/com/willwinder/universalgcodesender/ExperimentalWindow.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Version.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/WindowTitleUpdaterService.java
Attempt to fix problem with version string that generates an exception in parts of the code that expects a number. Issue #1156
=> Attempt to fix problem with version string 

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/lifecycle/startup.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/OverrideAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/OverrideActionService.java
Fixed bug where shortcut commands for overrides couldn't be executed when machine was running.  Also checks the controller for real time override support.
Fixes #1165
=> Fixed bug on shortcut commands for overrides 

scripts/svg_to_icons.sh
small changes to also be able to run `svg_to_icons.sh` on a linux machine
=> Adapt svg_to_icons.sh to run on linux and mac

README.md
add some hints to make it more easier to get the project running in Intellij
=> add hints on how to develop in intellij

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/Code.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/VisualizerPopupMenu.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/actions/JogToHereAction.java
=> The jog action in visualizer now shows the position in preferred units.

.idea/runConfigurations/UGS_Platform.xml
regarding https://github.com/winder/Universal-G-Code-Sender/pull/1218#issuecomment-487216322
=> import run netbeans platform config into repo

.idea/runConfigurations/UGS_Platform.xml, README.md
Use `ugs-platform-app` then the build dependencies are correct and intellij should build all classes correctly
=> fix readme and intellij run-config 

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPI.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/PartialPosition.java, ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/PartialPositionTest.java, ugs-core/test/com/willwinder/universalgcodesender/services/JogServiceTest.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/CoordinatesSubMenu.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/Visualizer2TopComponent.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/VisualizerPopupMenu.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/actions/JogToHereAction.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/actions/SetWorkingCoordinatesHereAction.java, ugs-platform/ugs-platform-visualizer/src/test/java/com/willwinder/ugs/nbm/visualizer/actions/JogToHereActionTest.java
Move the "Jog to...." into a submenu and a more coordinates-contextual options
- jog
- set offset
- copy
=> Refactor visualizer context - include option to jog or set offset 

ugs-core/src/com/willwinder/universalgcodesender/uielements/components/WorkCoordinateTextField.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/MachineStatusPanel.java
=> Increased precision for MM with 3 decimals in the DRO

ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroActionPanel.java, ugs-platform/ugs-platform-plugin-jog/src/test/java/com/willwinder/ugs/nbp/jog/LongPressMouseListenerTest.java
Fixed the refresh of the macros panel when updating macros.
Fixed a unit test that fails on slow computers.
=> Fixes the refreshing of macros panel and a unit test

new-module-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml, ugs-platform/DowelModule/pom.xml, ugs-platform/GcodeTools/pom.xml, ugs-platform/ProbeModule/pom.xml, ugs-platform/application/pom.xml, ugs-platform/branding/pom.xml, ugs-platform/pom.xml, ugs-platform/ugs-platform-gcode-editor/pom.xml, ugs-platform/ugs-platform-plugin-jog/pom.xml, ugs-platform/ugs-platform-plugin-setup-wizard/pom.xml, ugs-platform/ugs-platform-plugin-workflow/pom.xml, ugs-platform/ugs-platform-surfacescanner/pom.xml, ugs-platform/ugs-platform-ugscore/pom.xml, ugs-platform/ugs-platform-ugslib/pom.xml, ugs-platform/ugs-platform-visualizer/pom.xml, ugs-platform/ugs-platform-welcome-page/pom.xml
Possible fix for #1213. It does build and I can connect to GRBL.
=> Updated jSerialComm library

ugs-classic/release_files/start-cli.sh, ugs-classic/release_files/start.sh
Removed extra line breaks in script to make it possible to use as linux service
=> Removed extra line breaks

ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/ContinuousJogHandler.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanelButtonEnum.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java
This is a potential fix for the problems with continuous jogging hanging. I've moved the code for continuous jogging to its own handler which is responsible for checking if the command has entered GRBLs planner before issuing a cancel jog. It's not pretty but it looks like it's working.
Fixes #1126 and #1193
Thanks to @AlexHolden, @bdurbrow and @zeevy for helping out!
=> Fixed problem with continuous jogging hanging

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/services/JogServiceTest.java
Fixed issue where a faulty command was generated for GRBL jog to. 
G1 commands are not valid in combination with $J=.
Fixes #1273
=> Fix for jog-to-here command

ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/connection/ResponseMessageHandler.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/GcodeParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/errors/InvalidG2CommandErrorParser.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/windows/DiagnosticsTopComponent.java
Fixes problem with #1266 where g2core now returns json-null values in response.
Also added an error in editor for M0-commands as the controller ends up in IDLE-state unlike GRBL which ends up in HOLD-state. The M0-command needs to be fixed separately.
=> Fixed problem with new g2core firmware returning responses with null values

ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java
The status report configuration has changed where some options were removed. This causes the configuration from UGS to be invalid and some features has stopped working.
=> Fixed status report configuration

ugs-core/src/com/willwinder/universalgcodesender/G2CoreController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/types/TinyGGcodeCommand.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ControllerSettings.java, ugs-core/src/resources/firmware_config/g2core.json, ugs-core/test/com/willwinder/universalgcodesender/G2CoreControllerTest.java
TinyG is now usable, however some issues are still left: 
Fixes #1142 and addresses some of the issues in #1262
=> Fixed tinyg support

.travis.yml, ugs-platform/application/pom.xml, ugs-platform/pom.xml
Made an attempt to create a windows bundle that should be easier to start than downloading a jdk manually.
Potential fix for: #1254
=> Attempt to create a Windows bundle

.travis.yml, scripts/deploy.sh, ugs-platform/application/pom.xml, ugs-platform/pom.xml
Now reverted to using a JRE instead of JDK which cuts about 150Mb per package. Added linux package. Fixed paths for JRE in configs.
=> Changes to packaging

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/Capabilities.java, ugs-core/src/com/willwinder/universalgcodesender/CapabilitiesConstants.java, ugs-core/src/com/willwinder/universalgcodesender/G2CoreController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ActionButtonPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ConnectionSettingsPanel.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ReturnToZeroAction.java
Added setting for safety height when returning to home. Moved the returnToHome implementation to the abstract class as the implementation will work on all controllers. Added the "return to home" as a capability instead of letting the controller throw an exception if not implemented.
Fixes #1128
=> Added setting for safety height

ugs-core/src/com/willwinder/universalgcodesender/firmware/DefaultFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/IFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/grbl/GrblFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/tinyg/TinyGFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/utils/MathUtils.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelConnection.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelHardLimits.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelHoming.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelImportSettings.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelSoftLimits.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelStepCalibration.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/test/java/com/willwinder/ugs/nbp/setupwizard/SetupWizardTest.java
Fixes #1361
Steps per mm can now be set using decimals.
=> Setup Wizard now supports calibrating steps with decimals

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerStatus.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerStatusBuilder.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-core/test/com/willwinder/universalgcodesender/services/JogServiceTest.java
I've removed the usage of the state string and converted the places where this is used to the ControllerState instead.
=> Removed the usage of the controller state string

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/GcodeModel.java
Runs the vertex updates in its own thread but only allows one update at the time. This should fix some of the performance issues with large files with many small movements.
One way to confirm this is to use Bob's test file in #1278, my computer chokes after a couple of seconds. After this fix it works at least on my computer. =)
I think it also solves but have no way of confirming it: #1352, #655, #766,
=> Runs the vertex updates in its own thread but only allows one update at the time

ugs-core/src/com/willwinder/universalgcodesender/i18n/Localization.java, ugs-core/test/com/willwinder/universalgcodesender/i18n/LocalizationTest.java
Fixes a problem with negative numbers formatted with the UTF-8 symbol for minus sign (0xE2 0x88 0x92).
=> Fixed minus symbol

ugs-platform/ugs-platform-plugin-jog/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-plugin-jog/src/main/resources/com/willwinder/ugs/nbp/jog/Bundle.properties, ugs-platform/ugs-platform-plugin-jog/src/main/resources/resources/MessagesBundle.properties, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/resources/com/willwinder/ugs/nbp/setupwizard/Bundle.properties
Fixed the manifests for plugins so that the information is displayed properly in the plugins dialog.
=> Fixed the manifests for plugins so that the information is displayed properly

ugs-pendant/src/main/webapp/src/app/components/jog/jog.component.html, ugs-pendant/src/main/webapp/src/app/components/jog/jog.component.ts
=> Removed step size functionality as it wasn't longer possible to set a value manually on some devices.

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/CommandPanel.java
=> Now stores changes to the settings directly when changed.

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/service/JoystickServiceImpl.java
Added additional logging for debugging if a gamepad controller is connected
=> Added additional logging for debugging gamepad

README.md, ugs-core/src/com/willwinder/universalgcodesender/utils/Version.java
Now displays the maven version in title:
If it's a release, only the version number will be displayed. If it's a snapshot build the the date will be shown as well.
=> Version string from version number

pom.xml, ugs-core/src/com/willwinder/universalgcodesender/uielements/helpers/SteppedSizeManager.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ButtonGridPanel.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/uielements/components/CommandTextAreaTest.java, ugs-core/test/com/willwinder/universalgcodesender/uielements/panels/ButtonGridPanelTest.java, ugs-platform/application/pom.xml, ugs-platform/pom.xml, ugs-platform/ugs-platform-plugin-toolbox/pom.xml, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/ToolboxTopComponent.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/ActionReferenceRenderer.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/CategoryActionReference.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/DoubleClickDelegator.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/ISettingsListener.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/Settings.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/ToolboxOptionsController.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/ToolboxOptionsPanel.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/nbm/manifest.mf, ugs-platform/ugs-platform-plugin-toolbox/src/main/resources/com/willwinder/ugs/nbp/toolbox/Bundle.properties, ugs-platform/ugs-platform-plugin-toolbox/src/main/resources/com/willwinder/ugs/nbp/toolbox/down.svg, ugs-platform/ugs-platform-plugin-toolbox/src/main/resources/com/willwinder/ugs/nbp/toolbox/up.svg, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/options/AbstractOptionPanelController.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ActionRegistrationService.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/LocalizingService.java
This is new plugin for displaying actions in UGS. It has a reactive design and allows users to customize which actions that should be available.
Adresses these issues:
#219, #933, #1249
Default view when component is loaded the first time:
Is resizable and will adjust the number of columns:
---
It also allows customizing the actions from a settings panel:
=> Added a new toolbox component with customizable actions

ugs-core/src/com/willwinder/universalgcodesender/GrblCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodeParser.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/Position.java, ugs-core/src/com/willwinder/universalgcodesender/types/PointSegment.java, ugs-core/src/com/willwinder/universalgcodesender/visualizer/GcodeViewParse.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/processors/MeshLevelerTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/SurfaceScanner.java
Fixed more problems with missing units and conversion.
=> Fixed problems with missing unit conversion

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/renderer/EditorListener.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/renderer/EditorPosition.java
Added a editor cursor that is positioned on the currently highlighted line. This will be helpful when selecting "Run from..." in the editor.
=> Added a editor cursor that is positioned on the currently selected line

ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java
=> Reactivated keyboard shortcut for resetting position

ugs-core/src/com/willwinder/universalgcodesender/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/SmoothieUtils.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/DefaultFirmwareSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/SmoothieFirmwareSettings.java
Fixed problem with setting work position on Smoothieware causing errors because of missing units. 
Added Homing-capability.
=> Smoothieware

ugs-core/src/com/willwinder/universalgcodesender/gcode/processors/Translator.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/processors/TranslatorTest.java
=> Fixed problem with tiler plugin not rounding decimals

ugs-core/src/com/willwinder/universalgcodesender/uielements/components/RoundedPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/LongPressMouseListener.java, ugs-platform/ugs-platform-plugin-jog/src/test/java/com/willwinder/ugs/nbp/jog/LongPressMouseListenerTest.java
Fixes problem with mouse clicks when the mouse position changes between the press and release event.
Fixes #888
=> Fix for problem with mouse clicks

ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/WizardUtils.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/panels/WizardPanelStepCalibration.java
Now resets the controller when updating the step size configuration to force the controller to load the new settings.
Fixes #1424
=> Fixed problem with step size settings being loaded properly.

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/options/VisualizerOptions.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/Grid.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/MachineBoundries.java
Fixes: #1486
Adresses some issues in: #813
=> Fixed problem with visualizer axis colors being mapped the wrong way.

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/CommandPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/console/SerialConsoleTopComponent.java
Now selects command field when component is selected
Made it possible to bind a shortcut to the console window and automatically select the command field.
Fixes #1499
=> Now selects command field when component is selected

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java, ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/src/com/willwinder/universalgcodesender/model/Axis.java, ugs-core/src/com/willwinder/universalgcodesender/model/BackendAPI.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/PartialPosition.java, ugs-core/src/com/willwinder/universalgcodesender/services/JogService.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ContinuousJogWorker.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/G2CoreControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/TinyGControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/PartialPositionTest.java, ugs-platform/ugs-platform-plugin-setup-wizard/src/main/java/com/willwinder/ugs/nbp/setupwizard/NavigationButtons.java
Another small step towards supporting ABC axis in the backend.
=> Add ABC to PartialPosition, switch jog operations to use PartialPosition

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroService.java
=> Fixed problem with inactive macro actions, now listens to UGS events

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OutlineAction.java
=> Now uses the processed gcode file for outlining the work.

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java
I loaded my mega with gcarvin 2.0 and connected with these changes. I couldn't test all features as I got a door alarm but it seems like its working.
Fixes #1529
=> Added gCarvin to the list of controllers

ugs-core/src/com/willwinder/universalgcodesender/uielements/JScrollMenu.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/JScrollPopupMenu.java, ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/ui/BindActionButton.java
Adds scrollbars to the popup menu
Fixes #1416
=> Added scrollbars to the popup menu

ugs-platform/ugs-platform-plugin-joystick/src/main/resources/com/willwinder/ugs/nbp/joystick/gamecontrollerdb.txt
=> Added custom arduino joystick configuration

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/FirmwareAction.java
=> Now remembers which firmware that was selected

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ChangeCutSettingsAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/DeleteAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/selection/SelectionManager.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/SelectionSettingsPanel.java
Fixed bug for deleting groups
Made cut settings faster by not sending an event for each entity group the event for the whole selection.
=> Designer performance fixes

ugs-cli/src/main/java/com/willwinder/ugs/cli/ProcessedLinePrinter.java, ugs-cli/src/main/java/com/willwinder/ugs/cli/ProgressBarPrinter.java, ugs-cli/src/main/java/com/willwinder/ugs/cli/TerminalClient.java
* Added a wait period after sending homing and unlock commands
* Added handling when the stream is paused.
=> Added a wait period after sending homing and unlock commands

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ChangeToolSettingsAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/MultiplyDialog.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/PopupMenuFactory.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/StockSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/TextFieldWithUnit.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolBox.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/Unit.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/UnitFormatter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/model/Settings.java
Added units to settings textfields:
=> Added units to setting text fields

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OutlineAction.java, ugs-platform/ugs-platform-ugscore/src/test/java/com/willwinder/ugs/nbp/core/actions/OutlineActionTest.java
Now use the jog feed rate to create the outline.
Addresses #1757
=> Uses jog feed rate to generate outline

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/model/GUIBackendTest.java, ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/action/AnalogJogAction.java, ugs-platform/ugs-platform-plugin-joystick/src/test/java/com/willwinder/ugs/nbp/joystick/action/AnalogJogActionTest.java
Fixed problem with stopping during door state causing the machine to move instead of resetting. Also disabled any jogging during door state.
Addresses #1786
=> Fixed problem with stopping during door state

pom.xml, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/BreakApartAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ExportGcodeAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/MainMenu.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/EntityComparator.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/GcodeDesignWriter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/GcodePath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/PathGenerator.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/Segment.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/path/SegmentType.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/AbstractToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SimplePath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SimplePocket.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/ToolPathUtils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/ExportGcodeCookieAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsDataObject.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/EntityComparatorTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SimplePocketTest.java
Added a menu option for exporting the design as gcode. Cleaned up the gcode format and added some headers and comments.
=> Added the possibility to export a design as gcode

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/DesignerTopComponent.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/lifecycle/startup.java
Added option to open files using a default argument to the application. Should now be possible to associate a file type with UGS.
MacOSX doesn't work due to the more complex launcher api:s.
=> Added option to open files using a default argument to the application

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/shared/GcodeRenderer.java
=> Fixed problem with NPE when setting a coordinate that wasn't set in the status report

ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java
Attempt to fix intermittent failing test on the build server, moving the failing test to the GrblControllerTest class.
=> Attempt to fix intermittent failing test on the build server

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/GcodeDesignWriter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/UgsDesignWriter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/v1/SettingsV1.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/model/Settings.java
Starts the spindle with the defined speed in the beginning of the program. It will also shut the spindle down in the end of the program.
Fixes #1878
=> Starts the spindle when starting carving design

ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroActionPanel.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroSettingsPanel.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java
UGS just rocks!
However I had to apply the following patches to fix few stability issues:
1) A race condition that manifest itself from time to time in the forEach loop in updateCustomGcodeControls method of MacroActionPanel class is fixed:
```
---------------- On macro run ----------------
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Sending gcode command:  G10 P0 L20 Z0
SEVERE [com.willwinder.universalgcodesender.GrblController]: Error while processing response <<Run|MPos:-0.038,-0.028,0.000|FS:96,0>>
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1509)
```
2) In the MacroSettingsPanel class the findUniqueMacroName method can
throw a nullException because of empty macro name (fixed). The non-empty name check is not …
=> Several fixes to improve stability

ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStream.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStreamReader.java, ugs-core/src/com/willwinder/universalgcodesender/utils/GcodeStreamWriter.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodeParserTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/GcodeStreamReaderTest.java
=> Fixed problem with gcode files not loading with an empty first line.

ugs-core/src/com/willwinder/universalgcodesender/utils/ContinuousJogWorker.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanelButtonEnum.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogTopComponent.java
Added buttons for jogging ABC-axises. The buttons will be shown if the controller has capabilities for it and the user has chosen to activate the coordinate in the DRO:
=> Added buttons for jogging ABC-axises

ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/MachineStatusPanel.java
=> fix for issue 1928

.travis.yml, scripts/deploy.sh, ugs-platform/application/pom.xml, ugs-platform/pom.xml
Added support for Windows 64-bit by adding a 64-bit JRE.
=> Added support for Win64

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/JoystickOptionsPanel.java, ugs-platform/ugs-platform-plugin-toolbox/src/main/java/com/willwinder/ugs/nbp/toolbox/settings/ToolboxOptionsPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/options/MacrosPanel.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/options/AbstractOptionPanelController.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/options/AbstractOptionsPanel.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/options/VisualizerOptionsPanel.java
=> Reactivate joystick on canceling options

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/service/JoystickServiceImpl.java
these changes fix issue #1927 (crash on quit when joystick is enabled) , by moving all interaction with SDL into a single thread (the mainLoop thread). Additionally, the mainLoop was modified to handle the case where no controllers are connected, and continually repoll to look for controllers until one is found. If a controller is later disconnected, the event is not immediately detected by SDL, however when a new controller is connected it does cause the previous readLoop to throw a ControllerUnpluggedException which is converted to JoystickException and handled gracefully - this way controllers can be hot-plugged and unplugged at will and everything works as expected now.
=> these changes fix issue #1927

ugs-platform/ugs-platform-plugin-filebrowser/src/main/java/com/willwinder/ugs/nbp/filebrowser/FileBrowserDialog.java
Fixed a problem with selected file index in the file browser dialog
=> Delete the file at the selection index

ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java
=> Added FluidNC probing

.github/workflows/nightly.yaml
Added a build script for nightly builds that uses github actions and uploads artifacts to a github release
=> Build script for nightly builds

ugs-core/src/com/willwinder/universalgcodesender/gcode/processors/RunFromProcessor.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/services/RunFromService.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/highlight/RunFromHereHighlightContainer.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/GcodeParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/errors/ErrorParser.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/parser/errors/InvalidGcodeErrorParser.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OutlineAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ProgramAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/StartAction.java, ugs-platform/ugs-platform-ugscore/src/test/java/com/willwinder/ugs/nbp/core/actions/StartActionTest.java
=> Added abstract action that requires the gcode document to be saved before the file can be sent

.github/workflows/release.yaml
Added build script for building releases.
When a release/tag is created in the format v.X.Y.Z it will automatically build and upload the binaries to the release.
=> Release build script

ugs-core/src/com/willwinder/universalgcodesender/model/UGSEventDispatcher.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/components/CommandTextArea.java, ugs-core/src/com/willwinder/universalgcodesender/utils/CommandHistory.java, ugs-core/test/com/willwinder/universalgcodesender/utils/CommandHistoryTest.java, ugs-platform/ugs-platform-plugin-console/pom.xml, ugs-platform/ugs-platform-plugin-console/src/main/java/com/willwinder/ugs/nbp/console/ConsoleKeyListener.java
* Fix missing dependency which made the plugin fail to start
* Refactored command history, removing duplicate code
* Use CopyOnWriteArrayList to prevent concurrent modification errors
=> Fixs for new console plugin

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/highlight/GcodeHighlightsLayerFactory.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/highlight/RunFromHereHighlightContainer.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/highlight/SentCommandsHighlightContainer.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/Bundle.properties, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/FontAndColors.xml
=> Add highlight container for sent gcode commands in editor

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/StatusPollTimer.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ThreadHelper.java
Fixed concurrency problems for very fast file streams causing it to overwrite the `activeCommands` list.
Also decreased the number of worker threads to something more reasonable.
=> Fixed concurrency problems

ugs-core/src/com/willwinder/universalgcodesender/gcode/util/GcodeUtils.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/JogMachineToCenterAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/PopupMenuFactory.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/logic/Controller.java, ugs-platform/ugs-platform-plugin-designer/src/main/resources/img/jog-to.svg, ugs-platform/ugs-platform-plugin-designer/src/main/resources/img/jog-to24.svg, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/OutlineAction.java, ugs-platform/ugs-platform-ugscore/src/test/java/com/willwinder/ugs/nbp/core/actions/OutlineActionTest.java
=> Add action for jogging to center of an entity in the designer.

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/FollowLineUpdater.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeEditorKit.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/SourceMultiviewElement.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/FollowAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/actions/Bundle.properties, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/layer.xml, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/follow.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/follow24.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/follow32.svg
It will select the line that was last completed by the controller when using the toggle button in the editor.
=> Add action for following the running gcode in the editor

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/GcodeEditorKit.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/FollowAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/com/willwinder/ugs/nbp/editor/layer.xml, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/GlobalActionContextImpl.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/GlobalActionContextProxy.java
When a change has been made the DataObject gets a SaveCookie published. These cookies are however only available if the associated TopComponent has focus. This fix will work around that and add the save cookie to the global context.
=> Fixed problem with saving designs

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsDataObject.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsSaveAsCookie.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/UgsSaveCookie.java
Adds support for save the file with another name in the designer.
=> Add support for "Save as..." in the designer

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/GeometryToolpathComparator.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/ToolPathStats.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/ToolPathUtils.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/resources/pocket-test.ugsd
Improved the pocket tool path operation so that it generates about the half travel length. It will not lift the tool to safety height if it isn't necessary.
=> Optimised the tool path for pocket operation

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/MultiplyDialog.java
Add possibility to use decimals in spacing distance when multiplying objects in designer
=> Add possibility to multiply objects with a distance using decimals

ugs-classic/src/main/java/com/willwinder/universalgcodesender/KeyBoardListener.java, ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/LongPressKeyListener.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/LongPressMouseListener.java, ugs-core/test/com/willwinder/universalgcodesender/listeners/LongPressKeyListenerTest.java, ugs-core/test/com/willwinder/universalgcodesender/listeners/LongPressMouseListenerTest.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java, ugs-platform/ugs-platform-plugin-joystick/src/test/java/com/willwinder/ugs/nbp/joystick/action/ActionManagerTest.java, ugs-platform/ugs-platform-ugscore/pom.xml, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/ContinuousAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ContinuousActionExecutor.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ContinuousActionShortcutListener.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/JogAction.java, ugs-platform/ugs-platform-ugscore/src/test/java/com/willwinder/ugs/nbp/core/services/ContinuousActionExecutorTest.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ShortcutService.java
This is an attempt to fix the problem with keyboard shortcuts hanging when jogging. I have introduced a new type of action (ContinuousAction) that will intercept any keyboard shortcut and execute `actionActivate()` and `actionDeactivated()` on a long press. Any short press and release will trigger the normal `actionPerformed()`.
Potential fix for:
#1494
#779 (this will no longer be needed as the normal shortcuts will work)
#1600
#124
=> Intercept shortcuts and perform long press action

ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-core/pom.xml, ugs-core/src/com/willwinder/universalgcodesender/connection/AbstractConnectionDevice.java, ugs-core/src/com/willwinder/universalgcodesender/connection/Connection.java, ugs-core/src/com/willwinder/universalgcodesender/connection/ConnectionFactory.java, ugs-core/src/com/willwinder/universalgcodesender/connection/DefaultConnectionDevice.java, ugs-core/src/com/willwinder/universalgcodesender/connection/IConnectionDevice.java, ugs-core/src/com/willwinder/universalgcodesender/connection/JSSCConnection.java, ugs-core/src/com/willwinder/universalgcodesender/connection/JSSCConnectionDevice.java, ugs-core/src/com/willwinder/universalgcodesender/connection/JSerialCommConnection.java, ugs-core/src/com/willwinder/universalgcodesender/connection/JSerialCommConnectionDevice.java, ugs-core/src/com/willwinder/universalgcodesender/connection/LoopBackConnection.java, ugs-core/src/com/willwinder/universalgcodesender/connection/TCPConnection.java, ugs-core/src/com/willwinder/universalgcodesender/connection/WSConnection.java, ugs-core/src/com/willwinder/universalgcodesender/model/MdnsEntry.java, ugs-core/src/com/willwinder/universalgcodesender/services/MdnsService.java, ugs-core/src/com/willwinder/universalgcodesender/services/MdnsServiceListener.java, ugs-core/src/com/willwinder/universalgcodesender/utils/RefreshThread.java, ugs-core/src/com/willwinder/universalgcodesender/utils/Settings.java, ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-core/test/com/willwinder/universalgcodesender/mockobjects/MockConnection.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/BaudRateAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PortAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PortCellItem.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PortCellRenderer.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PortComboBoxModel.java
* Auto updates the list with serial ports and removed refresh button
* Add the port description to port selection combo box <br/><img width="334" alt="image" src="https://user-images.githubusercontent.com/8962024/221374544-165eedb5-837b-4ff4-8a3c-c9d8a95153ab.png">
* Add mDNS for discovering telnet services
* When using TCP connection driver it will change the labels for Port -> Host and Baud -> Port <br/><img width="554" alt="image" src="https://user-images.githubusercontent.com/8962024/221374599-bbe3a9f7-7f18-4bf9-8da9-7fce00d66553.png">
* Now uses JSerialComm by default on all platforms
=> Updates to the connection actions/UI

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/ContinuousActionShortcutListener.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ShortcutService.java
Fix problem with the shortcut service that only read default key mappings.
It will now listen to the key map settings and update a local cache.
=> Fix problem with the shortcut service 

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/UnionAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/AbstractEntity.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Path.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/dxf/DxfReader.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PortAction.java, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/ShortcutService.java
Added possibilty to read arcs from a DXF. All entities are read as single lines and to be able to union those to entity can be a bit tricky as there is no way for UGS to know how to stitch the lines. In that case you need to union small chunks at a time:
=> Added parser for DXF arcs

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/actions/ToolImportAction.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/eagle/EaglePnpReader.java
Added support for importing .mnt and .mnb files from eagle:
=> Added support for importing Eagle PNP files

ugs-core/src/com/willwinder/universalgcodesender/i18n/Localization.java, ugs-core/test/com/willwinder/universalgcodesender/i18n/LocalizationTest.java
Fix faulty encoding transformation, all message bundles should be enc…
=> Fix faulty encoding transformation

ugs-core/src/resources/firmware_config/fluidnc.json, ugs-core/src/resources/firmware_config/g2core.json, ugs-core/src/resources/firmware_config/grbl.json, ugs-core/src/resources/firmware_config/grbl_esp32.json, ugs-core/src/resources/firmware_config/smoothieboard.json, ugs-core/src/resources/firmware_config/tinyg.json
Rollback empty line processor as this will make the configuration incompatible with previous versions
=> Rollback empty line processor

ugs-core/test/com/willwinder/universalgcodesender/GrblControllerTest.java, ugs-platform/ugs-platform-plugin-cloud-storage/src/main/java/com/willwinder/ugs/nbp/S3FileSystemView.java, ugs-platform/ugs-platform-plugin-cloud-storage/src/main/java/com/willwinder/ugs/nbp/S3VirtualFile.java
Fixes #2205 tests that consistently fail when run in Windows
=> Fix tests under Windows

.idea/runConfigurations/UGS_Platform.xml, ugs-core/src/com/willwinder/universalgcodesender/TinyGUtils.java, ugs-core/src/com/willwinder/universalgcodesender/communicator/TinyGCommunicator.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/tinyg/commands/TinyGGcodeCommand.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/GeometryPositionComparator.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/PlatformUtils.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/FirmwareAction.java
Fixed a couple of problems with TinyG:
* Empty lines being sent to TinyG using JSON, the controller will not respond otherwise
* Added parsing of odd ok/error responses from the controller
* Ensures that the controller is using single step mode only
* Fixed problem with the positions not being immutable
=> Bugfixes for TinyG

ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblControllerInitializer.java
Fixed a problem with grblHAL where certain responses were treated as parser state commands.
=> Fixed a problem with grblHAL

ugs-core/src/com/willwinder/universalgcodesender/firmware/grbl/GrblVersion.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/grbl/GrblVersionTest.java
=> Handle new variant of Genmitsu version string

ugs-core/src/resources/MessagesBundle_en_US.properties, ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeTopComponent.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/InsertPositionAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/actions/RunFromAction.java, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position24.svg, ugs-platform/ugs-platform-gcode-editor/src/main/resources/icons/position32.svg, ugs-platform/ugs-platform-ugslib/src/main/java/com/willwinder/ugs/nbp/lib/services/LocalizingService.java
Added action for inserting the current work coordinate into the cursor position in the gcode:
=> Add feature for inserting the current position into the open gcode file.

ugs-classic/src/main/java/com/willwinder/universalgcodesender/MainWindow.java, ugs-classic/src/main/java/com/willwinder/universalgcodesender/visualizer/VisualizerPanel.java, ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetAlarmCodesCommand.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetErrorCodesCommand.java, ugs-core/src/com/willwinder/universalgcodesender/listeners/ControllerListener.java, ugs-core/src/com/willwinder/universalgcodesender/model/GUIBackend.java, ugs-core/src/com/willwinder/universalgcodesender/model/UGSEventDispatcher.java, ugs-core/src/com/willwinder/universalgcodesender/model/events/FileStateEvent.java, ugs-core/test/com/willwinder/universalgcodesender/AbstractControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCControllerTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetAlarmCodesCommandTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetErrorCodesCommandTest.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java
Added missing event for when the file stream is finished to FluidNC.
Removed the file name from the FileStateEvent as it felt unintuitive that it sometimes was the processed gcode file sometimes the actual gcode file or null.
=> Added "stream finished" event for FluidNC

ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/ConnectionSettingsPanel.java
Small fix to disable the safety height feature when returning to zero.
#2303
=> Made it possible to set the return to zero safety height to zero

ugs-core/src/com/willwinder/universalgcodesender/uielements/macros/MacroSettingsPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/MacroService.java
* Added macro description as a tooltip
* Fixed so that the macro editing panel no longer overflows when adding long macros
* Now only use macro name in menus and toolbox
=> Add macro description as a tool tip

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java
Now reads the pin state immediately using the same status parser as GRBL. Also added the "open door" feature.
=> Display the pin status immediately in FluidNC

ugs-core/src/com/willwinder/universalgcodesender/Utils.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/helpers/ThemeColors.java, ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/CoordinateLabel.java, ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/MachineStatusPanel.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/statusline/ControllerStatusLineService.java
=> Changed DRO colors to have more contrast making them easier to read

ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/driver/JamepadJoystickDriver.java, ugs-platform/ugs-platform-plugin-joystick/src/main/java/com/willwinder/ugs/nbp/joystick/model/JoystickState.java
=> Wait for the controller to initialize before reading data to avoid getting junk.

ugs-core/pom.xml, ugs-platform/ugs-platform-ugslib/pom.xml
=> Replaced the script engine graalwm with nashorn

pom.xml, ugs-platform/ugs-platform-plugin-designer/pom.xml
=> Add missing dependency for jide-oss with flatlaf

ugs-core/src/com/willwinder/universalgcodesender/uielements/components/Spinner.java, ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/ui/AutoLevelerPanel.java
=> Add possibility to autolevel scan in negative space

ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/RendererInputHandler.java
=> Fixes mouse position on windows using scaled desktop

ugs-platform/ugs-platform-gcode-editor/pom.xml
=> Added library for editor search

ugs-platform/ugs-platform-gcode-editor/src/main/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexer.java, ugs-platform/ugs-platform-gcode-editor/src/test/java/com/willwinder/ugs/nbp/editor/lexer/GcodeLexerTest.java
=> Handle nested block comments and plus signs in coordinates

ugs-core/src/com/willwinder/universalgcodesender/AbstractController.java, ugs-core/src/com/willwinder/universalgcodesender/GrblController.java, ugs-core/src/com/willwinder/universalgcodesender/IController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCController.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCSettings.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetFirmwareSettingsCommand.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/smoothie/SmoothieController.java, ugs-core/src/com/willwinder/universalgcodesender/types/CommandException.java, ugs-core/src/com/willwinder/universalgcodesender/utils/ControllerUtils.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetFirmwareSettingsCommandTest.java, ugs-core/test/com/willwinder/universalgcodesender/utils/ControllerUtilsTest.java
=> Add better error message when FluidNC configuration is broken

ugs-pendant/src/main/webapp/src/components/AccessoryState.tsx, ugs-pendant/src/main/webapp/src/components/Header.tsx, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/PendantAction.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/panels/QRPanel.java, ugs-platform/ugs-platform-ugscore/src/main/resources/resources/images/cell-phone.svg, ugs-platform/ugs-platform-ugscore/src/main/resources/resources/images/cell-phone_dark.svg, ugs-platform/ugs-platform-ugscore/src/main/resources/resources/images/cell-phone_disabled_dark.svg
Fixed the pin status in the web pendant and also fine tuned the pendant start action, making the link clickable.
=> Pendant pin status

ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/FluidNCCommand.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetFirmwareSettingsCommand.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/commands/GetFirmwareSettingsCommandTest.java
=> Filter messages from command response

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/LaserFillToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/LaserFillToolPathTest.java
Fixes problems with extra line segments:
=> Fix problem with extra line segments on multipoint intersections

ugs-core/src/com/willwinder/universalgcodesender/CapabilitiesConstants.java, ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-platform/ugs-platform-visualizer/src/main/java/com/willwinder/ugs/nbm/visualizer/renderables/MachineBoundries.java
=> Make machine boundaries handle inversed homing positions

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/DrillCenterToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/DrillCenterToolPathTest.java
=> Use rapid movement when drilling on up

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CutType.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/CutTypeIcon.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/v1/CutTypeV1.java
Added a new type of toolpath which can be used for surfacing a material.
=> Add new tool path option for surfacing

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/Utils.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntitySetting.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CutType.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Cuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CuttableEntitySettings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Group.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsModel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/UgsDesignWriter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/v1/CuttableEntityV1.java
Made it so that the shape to be surfaced will be done on the bounds of the object. It is also possible to add a tool offset to make the surfacing tool start outside of the material.
=> Added possibility to offset the surfacing tool path

ugs-platform/ugs-platform-plugin-workflow/src/main/java/com/willwinder/ugs/nbm/workflow/WorkflowWindowTopComponent.java
Do not automatically add gcode files to workflow helper to fix it preventing loading design files.
=> Fix loading files in workflow helper

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/EntitySetting.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Cuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/CuttableEntitySettings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/Group.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsModel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/UgsDesignWriter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/ugsd/v1/CuttableEntityV1.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPathTest.java
Change the surface offset to two settings for lead in/out:
=> Change surface offset to lead in/out

ugs-platform/ugs-platform-gcode-editor/pom.xml, ugs-platform/ugs-platform-ugslib/pom.xml
=> Include missing classes from package

ugs-platform/ProbeModule/src/main/java/com/willwinder/ugs/platform/probe/ProbeService.java, ugs-platform/ProbeModule/src/test/java/com/willwinder/ugs/platform/probe/ProbeServiceTest.java
Z probing will be done using the retract amount plus 20% to avoid soft limits
=> Fix for soft limit alarms when probing

ugs-core/src/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtils.java, ugs-core/test/com/willwinder/universalgcodesender/gcode/GcodePreprocessorUtilsTest.java
=> Handle inline block comments

ugs-core/src/com/willwinder/universalgcodesender/utils/AutoLevelSettings.java, ugs-core/test/com/willwinder/universalgcodesender/utils/AutoLevelSettingsTest.java
=> Make sure the z-retract can't be smaller than the minimum value

ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/services/OverrideAction.java
=> Fix override action serialization to be able to add it to the toolbox

ugs-fx/build-linux-x64.sh, ugs-fx/build-macosx-aarch64.sh, ugs-fx/build-macosx-x64.sh, ugs-fx/build-windows-x64.bat, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/overlay/OverlayPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/FirmwareSettingTableCell.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/FirmwareSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/GeneralSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/MacroSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/stage/SettingsStage.java, ugs-fx/src/main/resources/icons/ugs.svg, ugs-fx/src/main/resources/styles/overlay-pane.css
Experimented with adding a new panel for functions such as probing, terminal and running a program:
https://github.com/user-attachments/assets/8aee2ac5-4023-4389-acb8-60d6813f8847
There is now also a installer for MacOSX
=> More FX fixes

ugs-core/src/com/willwinder/universalgcodesender/types/FxSettings.java, ugs-fx/pom.xml, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/Main.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/jog/JogPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/FirmwareSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/PendantSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/settings/VisualizerSettingsPane.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/Axes.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/GcodeModel.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/GcodeModelMaterial.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/Grid.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/OrientationCube.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/OrientationCubeFace.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/Tool.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/ToolAnimatorTimer.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/component/visualizer/Visualizer.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/helper/Colors.java, ugs-fx/src/main/java/com/willwinder/universalgcodesender/fx/stage/SettingsStage.java, ugs-fx/src/main/resources/styles/root.css
Added visualizer color settings. The tool position is now also being interpolated and is smooth.
=> Added visualizer color settings

ugs-core/src/com/willwinder/universalgcodesender/Utils.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/SoftResetAction.java
Fixes #2789
https://github.com/user-attachments/assets/426a9475-142a-4df3-a147-eb8da71a9583
=> Make it possible to reset controller in sleep mode

ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java, ugs-core/src/com/willwinder/universalgcodesender/Utils.java, ugs-core/src/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtils.java, ugs-core/test/com/willwinder/universalgcodesender/GrblUtilsTest.java, ugs-core/test/com/willwinder/universalgcodesender/firmware/fluidnc/FluidNCUtilsTest.java, ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/actions/SoftResetAction.java
=> Reset controller when starting in sleep mode

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/ToolSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/SimpleGcodeRouter.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/model/Settings.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/platform/SettingsAdapter.java
This PR will fix:
https://github.com/winder/Universal-G-Code-Sender/issues/2820
=> Set spindle direction

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/dxf/DxfReader.java
Fixes the importing problem in #2840
=> Invert arc angles since the coordinate system of the DXF is different

README.md, run_platform.bat, ugs-core/src/com/willwinder/universalgcodesender/model/Axis.java, ugs-core/src/com/willwinder/universalgcodesender/uielements/panels/OverridesPanel.java, ugs-platform/ugs-platform-plugin-dro/src/main/java/com/willwinder/ugs/nbp/dro/panels/MachineStatusPanel.java, ugs-platform/ugs-platform-plugin-jog/src/main/java/com/willwinder/ugs/nbp/jog/JogPanel.java
I added a section for code documentation with a basic overview of the project and a few comments in the code.
Please note that this is my first pull request, so if I did anything unusual, please let me know and I'll try to fix it.
=> Add more documentation

ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/entities/cuttable/AbstractCuttable.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/gui/selectionsettings/SelectionSettingsPanel.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/AbstractToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/DrillCenterToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/main/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPath.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/DrillCenterToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/OutlineToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/PocketToolPathTest.java, ugs-platform/ugs-platform-plugin-designer/src/test/java/com/willwinder/ugs/nbp/designer/io/gcode/toolpaths/SurfaceToolPathTest.java
Added support for setting negative start and target depths. This will make it possible to zero work position from the bed.
=> Allow negative start and target depths
